### ISSUE TITLE
Right side drawer not fully hidden when closed

### ISSUE THREAD

**Issue by jcgertig** [react-navigation/react-navigation#10335]
### Current behavior

When the drawer is on the right and closed it is still visible by I assume 20% of the width of the screen.

![Screen Shot 2022-02-08 at 11 17 42 PM](https://user-images.githubusercontent.com/455355/153126974-10e56bcf-6b1a-4ad3-b1d7-bf9f07fd7b9d.png)

![Screen Shot 2022-02-08 at 11 17 35 PM](https://user-images.githubusercontent.com/455355/153126976-dac8e8f7-ab74-4bdb-b0e2-abb454c65596.png)

### Expected behavior

Should be hidden when closed

### Reproduction

https://github.com/jcgertig/rnn-drawer-issue

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.0.8
| @react-navigation/drawer               | 6.3.1
| @react-navigation/native-stack         | 6.5.0
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.10.2
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.4.1
| react-native                           | 0.67.2
| node                                   | 14.17.4
| yarn                            | 1.22.17

**Comment by jcgertig** [comment]
From quick tests changing line 323 in `modern/Drawer.tsx` to `drawerType === 'permanent' || isRight ? 'row-reverse' : 'row',` it is fixed but Im not sure if that has any impact otherwise.

**Comment by jcgertig** [comment]
Found a better fix in the pr

**Comment by jcgertig** [comment]
Bump

**Comment by wandersonalwes** [comment]
That solved it for now
```shell
yarn add @react-navigation/drawer@6.1.8
```

**Comment by rxprmchs** [comment]
> That solved it for now
> 
> ```shell
> yarn add @react-navigation/drawer@6.1.8
> ```

Still encountering the bug on this version. Hopefully, @jcgertig's pr get merged soon.

**Comment by SohelIslamImran** [comment]
I'm also facing the issue. I spend a lot of time to solve the problem, but couldn't. Then found this issue. Please solve this issue ASAP.

**Comment by SohelIslamImran** [comment]
> I found that setting the `useLegacyImplementation` prop on the drawer navigator to `true` has temporarily solved this issue for me. Obviously this has the downside of a forced downgrade to reanimated v1.

Hey! Is this OK to use that? @chvanlennep

**Comment by SohelIslamImran** [comment]
And one more thing, **not only visible** around 20% **but also draggable right to left and left to right on android**.

**Comment by rxprmchs** [comment]
> I found that setting the `useLegacyImplementation` prop on the drawer navigator to `true` has temporarily solved this issue for me. Obviously this has the downside of a forced downgrade to reanimated v1.

Adding this prop worked! Will use this temporary fix for now, thanks.

**Comment by leepowellnbs** [comment]
Temp solution for me was to:
```
drawerStyle: {
  width: '95%',
  right: 0 <-- this!
},
```

**Comment by Srh07** [comment]
First of all: this works! Thanks @leepowellnbs! You're a lifesaver!

> Temp solution for me was to:
> 
> ```
> drawerStyle: {
>   width: '95%',
>   right: 0 <-- this!
> },
> ```

I can also confirm the same issue occurs on iPad. In landscape the drawer is permanent opened in the middle of the screen. When pressing the icon to open the drawer, a blank canvas appears on the right side of the screen while the "permanent opened drawer" doesn't do anything. When drawerPosition set to "left" there's no issue.

**Comment by ryderdonahue** [comment]
The above PR does not fix this issue, it reproduces on 6.6.2 and Reanimated v3.
The Reanimated V3 part is important because with it you are no longer able to `useLegacyImplementation` which was a fix to this issue.

**Comment by MrSquaare** [comment]
This problem still exists with `@react-navigation/drawer@6.6.3` and `react-native-reanimated@3.3.0`

**Comment by ossraju** [comment]
This problem still exists with @react-navigation/drawer@6.6.2 and react-native-reanimated@3.3.0.
Any fix

**Comment by brimby** [comment]
Yeah I've still got this. Only on ios, left side drawer. It only hangs open part of the time and I can't figure out what triggers it.

**Comment by SwikarBhattarai** [comment]
> ```js
> const width = Dimensions.get("window").width;
> ```

this didn't work while testing in testflight.

**Comment by henryteng07** [comment]
> Temp solution for me was to:
> 
> ```
> drawerStyle: {
>   width: '95%',
>   right: 0 <-- this!
> },
> ```

This works!

**Comment by JairajJangleSLIOT** [comment]
Can we re-open this issue please?

**Comment by JairajJangleSLIOT** [comment]
> First of all: this works! Thanks @leepowellnbs! You're a lifesaver!
> 
> > Temp solution for me was to:
> > ```
> > drawerStyle: {
> >   width: '95%',
> >   right: 0 <-- this!
> > },
> > ```
> 
> I can also confirm the same issue occurs on iPad. In landscape the drawer is permanent opened in the middle of the screen. When pressing the icon to open the drawer, a blank canvas appears on the right side of the screen while the "permanent opened drawer" doesn't do anything. When drawerPosition set to "left" there's no issue.
> 
> Edit: I found out that downgrading to Reanimated v2.2.4 solves the problem without the fix with "right: 0". I encountered another issue in react-devtools. My app kept loading and wasn't responding anymore when in debug mode. So I downgraded to reanimated 2.2.4 because I knew this version was working in another app. It's not ideal to downgrade, but at least it's still reanimated v2. I hope this helps someone.
> 
> Edit2: After testing on a lot of iPad devices the issue still persisted. I'd like to refer to issue #10418 in which the fix is to downgrade the drawer to 6.3.0. I can confirm this works, it's a smaller downgrade than recommended in the above comments.

Downgrading to 6.3.0 fixed the issue for me as well, definitely something went wrong in 6.3.0+ releases

**Comment by tofujlg** [comment]
Still facing the issue in `@react-navigation/drawer@6.6.6`.
This issue only happens when I open in-app-browser and open OS keyboard.

**Comment by Coreeze** [comment]
> For me it happened only when drawer had custom width by percentage to fix it I removed the percentage and added this line instead and this fixed it.
> 
> ```js
> const width = Dimensions.get("window").width;
> 
> ....
> 
> drawerStyle: {
>           width: width * 0.8,
>         },
> ```

Hero.

Removed my custom width and problem solved. Finally.

**Comment by sepehrsohrabii** [comment]
> Temp solution for me was to:
> 
> ```
> drawerStyle: {
>   width: '95%',
>   right: 0 <-- this!
> },
> ```

Perfect
