### ISSUE TITLE
KeyboardAvoidingView not working with header and material-bottom-tabs on iOS

### ISSUE THREAD

**Issue by tomwaitforitmy** [react-navigation/react-navigation#10583]
### Current behavior

KeyboardAvoidingView does not avoid the keyboard correctly, if you use a header and material-bottom-tabs on iOS. For Android, everything works out of the box. You can find a more detailed description with a screenshot on stack overflow: [https://stackoverflow.com/questions/71464805/keyboardavoidingviev-not-working-with-react-navigation-header-and-material-botto/71466874?noredirect=1#comment126334051_71466874](https://stackoverflow.com/questions/71464805/keyboardavoidingviev-not-working-with-react-navigation-header-and-material-botto/71466874?noredirect=1#comment126334051_71466874)

A fixed offset helps out a bit, until you close the keyboard. See screenshot on stack overflow.

### Expected behavior

It should obviously avoid the keyboard. 

### Reproduction

https://github.com/tomwaitforitmy/keyboardAvoidingViewAndNavigation

https://snack.expo.dev/@tomwaitforitmy/keyboardavoidingview

You can clearly see the issue in the snack:
![grafik](https://user-images.githubusercontent.com/25305424/168467048-e2442332-3b72-41b6-94e8-c974dadc4b32.png)

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [X] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
    "@react-navigation/elements": "^1.3.3",
    "@react-navigation/material-bottom-tabs": "^6.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native": "0.64.3",
    "expo": "^44.0.6",

**Comment by tomwaitforitmy** [comment]
Anything I can do so that this receives any attention?

**Comment by tomwaitforitmy** [comment]
Bump

**Comment by raajnadar** [comment]
Can you make your repro minimal? So it is easier to debug the issue, please remove the not required code to repro the issue

**Comment by tomwaitforitmy** [comment]
@raajnadar Did you have a look my Snack? What exactly is confusing for you? Here is a brief summary what is required to repro:
* Material Bottom Tab Navigator (MainTabNavigator inside TestNavigationContainer)
* Stack Navigator with at least one screen inside that Tab Navi (DevStack inside TestNavigationContainer)
* One Screen filled with any dummy elements (I choose 30 buttons) plus a <TextInput> that should be avoided by     <KeyboardAvoidingView>, but it is not.

If you remove anything more like the Material Bottom Tab or the Stack Navigator, it is not repro. Most of the code is boilerplate code from either react native or react navigation. I added styling (red background and padding) to make the issue more visible. I doubt it would help much if I remove these two lines. All 4 .js files combined don't even have 150 lines of code.

**Comment by raajnadar** [comment]
So the issue was temporarily solved by replacing material bottom tabs with bottom tabs right?

**Comment by tomwaitforitmy** [comment]
Exactly, not repro with bottom tabs. Only with material bottom tabs.

**Comment by raajnadar** [comment]
As per the maintainers of react native paper, this will be solved in the next RC of v5 https://github.com/callstack/react-native-paper/issues/3272#issuecomment-1219292863

we can close this once the paper version is bumped in the react-navigation

**Comment by raajnadar** [comment]
Closing as React native paper has a stable release v5

**Comment by tomwaitforitmy** [comment]
@raajnadar I recently updated my minimal not working example to react-native-paper 5.2.0. See here:
https://snack.expo.dev/@tomwaitforitmy/keyboardavoidingview

The bug is still there. Did I do anything wrong or did you not fix it?
