### ISSUE TITLE
Navigator screenOptions `headerBackTitleVisible: false` is ignored on the first navigation into the stack

### ISSUE THREAD

**Issue by brentfrederick** [react-navigation/react-navigation#11337]
### Current behavior

For example in the setup below, on the `Signup` screen, the "Back" label incorrectly appears. On all subsequent screens, the "Back" label is properly hidden.

After more testing, it appears that the first navigation into the stack will ignore `headerBackTitleVisible: false`, and subsequent navigations within the stack will hide it properly.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/10117597/232895442-9bd4d08f-ba97-4da9-9856-66bcffb7a8cb.png">
<img width="413" alt="image" src="https://user-images.githubusercontent.com/10117597/232895534-68220460-2deb-4b4f-b831-104bd68279f3.png">

```
    <RootStack.Navigator
      screenOptions={{
        headerShown: true,
        headerShadowVisible: false,
        headerTitleAlign: 'center',
        headerTintColor: tintColor,
        headerBackTitleVisible: false,
        headerTitleStyle: {
          color: 'black',
        },
      }}>
      <RootStack.Screen
        name="Login"
        component={LoginScreen}
        options={{
          headerShown: false,
        }}
      />
      <RootStack.Screen
        name="Signup"
        component={SignupScreen}
        options={{title: 'Sign up'}}
      />
      <RootStack.Screen
        name="SignupConfirm"
        component={SignupConfirmScreen}
        options={{title: 'Enter confirmation code'}}
      />
```

### Expected behavior

The "Back" label is hidden on all screens.

### Reproduction

https://snack.expo.dev/MEvNWyFtP

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/material-bottom-tabs": "^6.2.15",
    "@react-navigation/material-top-tabs": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",

**Comment by itajenglish** [comment]
+1

**Comment by nguyendat0410** [comment]
+1 Same problem here

**Comment by mo-fouad** [comment]
+1 Same Issue

**Comment by itajenglish** [comment]
Hi Guys, I created a [patch file](https://gist.github.com/itajenglish/5c8f61e19b829f07fb3220da69fa5b82) of the fix merged in the react-native-screens [PR](https://github.com/software-mansion/react-native-screens/pull/1726). I will however warn that I experienced nested navigators still showing back titles but navigating to root screens no longer shows. See the comment I left [here](https://github.com/software-mansion/react-native-screens/pull/1726#issuecomment-1518935590). Hope this helps for now until we get a fix.

**Comment by drdpedroso** [comment]
> Hi Guys, I created a [patch file](https://gist.github.com/itajenglish/5c8f61e19b829f07fb3220da69fa5b82) of the fix merged in the react-native-screens [PR](https://github.com/software-mansion/react-native-screens/pull/1726). I will however warn that I experienced nested navigators still showing back titles but navigating to root screens no longer shows. See the comment I left [here](https://github.com/software-mansion/react-native-screens/pull/1726#issuecomment-1518935590). Hope this helps for now until we get a fix.

thank you for the patch! Did you manage to make it work on nested navigators or have any possible workarounds?

**Comment by itajenglish** [comment]
> > Hi Guys, I created a [patch file](https://gist.github.com/itajenglish/5c8f61e19b829f07fb3220da69fa5b82) of the fix merged in the react-native-screens [PR](https://github.com/software-mansion/react-native-screens/pull/1726). I will however warn that I experienced nested navigators still showing back titles but navigating to root screens no longer shows. See the comment I left [here](https://github.com/software-mansion/react-native-screens/pull/1726#issuecomment-1518935590). Hope this helps for now until we get a fix.
> 
> thank you for the patch! Did you manage to make it work on nested navigators or have any possible workarounds?

@drdpedroso Unfortunately, the workaround I came up with for now was to manually add the [React Navigation Elements](https://reactnavigation.org/docs/elements/) `HeaderBackButton` to all the screens that the fix didn't work on. It was a pain because we have a lot of nested screens 😢.

**Comment by ManRouss** [comment]
+1 same problem here
Any solution for this issue? thanks

**Comment by comontes** [comment]
+1 Same issue here 😢

**Comment by drdpedroso** [comment]
> > > Hi Guys, I created a [patch file](https://gist.github.com/itajenglish/5c8f61e19b829f07fb3220da69fa5b82) of the fix merged in the react-native-screens [PR](https://github.com/software-mansion/react-native-screens/pull/1726). I will however warn that I experienced nested navigators still showing back titles but navigating to root screens no longer shows. See the comment I left [here](https://github.com/software-mansion/react-native-screens/pull/1726#issuecomment-1518935590). Hope this helps for now until we get a fix.
> > 
> > 
> > thank you for the patch! Did you manage to make it work on nested navigators or have any possible workarounds?
> 
> @drdpedroso Unfortunately, the workaround I came up with for now was to manually add the [React Navigation Elements](https://reactnavigation.org/docs/elements/) `HeaderBackButton` to all the screens that the fix didn't work on. It was a pain because we have a lot of nested screens 😢.

thank you, that was the solution I ended up doing as well, so far so good :)

**Comment by caposaric** [comment]
I'm experiencing the same, though I think the original issue title describes the problem better: whenever my initial screen has `headerShown: false`, the very next one ignores `headerBackTitleVisible: false`. If I remove `headerShown: false`, it works just fine.

**Comment by kacperkapusciak** [comment]
Fixed in `react-native-screens@3.21.1` and `@react-navigation/native-stack@6.9.13`. 

Cheers ✌️

**Comment by EKOLX** [comment]
> Fixed in `react-native-screens@3.21.1` and `@react-navigation/native-stack@6.9.13`.
> 
> Cheers ✌️

With these updates still facing the issue

**Comment by lokibyte** [comment]
> I'm experiencing the same, though I think the original issue title describes the problem better: whenever my initial screen has `headerShown: false`, the very next one ignores `headerBackTitleVisible: false`. If I remove `headerShown: false`, it works just fine.

any solution for this issue?

**Comment by xyn22** [comment]
How come this issue is closed? It's not fixed, am I missing something?

**Comment by comontes** [comment]
> How come this issue is closed? It's not fixed, am I missing something?

For me the new versions quoted fixed the issue, in Expo I had to rebuild my Expo Dev Client to see changes.

**Comment by comontes** [comment]
> Also, @xyn22 If you aren't on Expo 49 and using Expo Go it might not work for you. See this response https://github.com/react-navigation/react-navigation/issues/11437#issuecomment-1607020118

I'm using Expo Dev Client with Expo 48 and it also works btw

**Comment by itajenglish** [comment]
@comontes Expo Dev Client and Expo Go are a little different. According to the person who made the fix devs using Expo Go wouldn't get to apply the change unless they are on Expo 49, only devs using Expo Dev Client can on versions prior to 49. I'm glad to hear it's working on 48 using dev client I haven't gotten a chance to apply the fix yet myself.

**Comment by itajenglish** [comment]
> > Also, @xyn22 If you aren't on Expo 49 and using Expo Go it might not work for you. See this response [#11437 (comment)](https://github.com/react-navigation/react-navigation/issues/11437#issuecomment-1607020118)
> 
> I'm using Expo Dev Client with Expo 48 and it also works btw

Expo Dev Client and Expo Go are a little different. According to the person who made the fix devs using Expo Go wouldn't get to apply the change unless they are on Expo 49, only devs using Expo Dev Client can on versions prior to 49. I'm glad to hear it's working on 48 using dev client I haven't gotten a chance to apply the fix yet myself.

**Comment by comontes** [comment]
> > > Also, @xyn22 If you aren't on Expo 49 and using Expo Go it might not work for you. See this response [#11437 (comment)](https://github.com/react-navigation/react-navigation/issues/11437#issuecomment-1607020118)
> 
> > 
> 
> > I'm using Expo Dev Client with Expo 48 and it also works btw
> 
> 
> 
> Expo Dev Client and Expo Go are a little different. According to the person who made the fix devs using Expo Go wouldn't get to apply the change unless they are on Expo 49, only devs using Expo Dev Client can on versions prior to 49. I'm glad to hear it's working on 48 using dev client I haven't gotten a chance to apply the fix yet myself.

Aaah I get it, thanks

**Comment by djmarcosban** [comment]
fix with Expo 49, react-native-screens@3.21.1 and @react-navigation/native-stack@6.9.13.

**Comment by JonathanSeehagen** [comment]
> fix with Expo 49, react-native-screens@3.21.1 and @react-navigation/native-stack@6.9.13.

It works fine. Thank you!

It also happened with me when I do another sdk expo update in my project. I don't understand why the headerBackTitleVisible don't work.

**Comment by TheRealMikeD** [comment]
Just to throw in an additional data point, I was having a somewhat similar issue, in which the back title was correctly hidden while developing in the dev client, when `headerBackTitleVisible` was set to `false`, but it was being displayed in stand-alone builds.  Super-annoying.

I fixed it by setting the `headerBackImage` option of the stack to a function that returns a back image which basically just tries to emulate the default back image for the platform: 
```
function getNavBackImg({tintColor}) {
    if (Platform.OS === 'android') {
        return (
            <FontAwesome6 name="arrow-left" size={20} color={tintColor}/>
        );
    } else {
        return (
            <Entypo name="chevron-small-left" size={40} color={tintColor}/>
        );
    }
}
```

This seemed to work in a test stand-alone build.  Hope this helps someone.

**Comment by haixiangyan** [comment]
Just simply use this work for me 😂
```
headerBackTitle: '',
```
