### ISSUE TITLE
Search bar not rendering on iOS or Android on initial render

### ISSUE THREAD

**Issue by homit-dalia** [react-navigation/react-navigation#11627]
### Current behavior

In the initial render of the search bar through headerSearchBarOptions, it will not render. I have 4 bottom tabs and each has its own stack navigator. Search Icon does not render on initial load but would load after I switch to another tab and then current tab.

### Expected behavior

The search icon should render on the first render of the screen

### Reproduction

https://github.com/react-navigation/react-navigation/issues/10848

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| node                                   |
| npm or yarn                            |

**Comment by Acetyld** [comment]
Any update on this?

**Comment by homit-dalia** [comment]
I initially set headerSearchBarOptions to true as the documentation stated that you should render atleast the UI elements in stack screens if you will update it on screen mount through .setOptions in useEffect (functional components). That was the problem. I removed headerSearchBarOptions in stack screen entirely and and now declaring it directly through .setOptions. I don't know if this is expected or headerSearchBarOptions : true is for a different context.

**Comment by Robert27** [comment]
Any updates or workarounds? :/

**Comment by homit-dalia** [comment]
> Any update on this?

I’m sorry @Robert27, but it fixed it for me after I removed headerSearchBarOptions: true in declaration and rebuilt the app.

However, it could also be an issue with if you are rendering other icons in headerRight. Try playing around the placement of those icons and see if it works.

**Comment by JcbPrn** [comment]
Still not working for me with the latest versions. What about you guys?

**Comment by nandorojo** [comment]
Hey guys, I think I fixed it by setting `hideWhenScrolling: false`:

```tsx
  const navigation = useNavigation<Screen>()
  useLayoutEffect(() => {
    navigation.setOptions({
      headerSearchBarOptions: {
        placeholder: 'Search...',
        onCancelButtonPress: actions.stopSearching,
        onFocus: actions.startSearching,
        onChangeText: (e) => actions.onChangeText(e.nativeEvent.text),
        hideWhenScrolling: false,
      },
    })
  }, [actions, navigation])
```

Let me know if this fixes it for you

**Comment by vbornand** [comment]
@nandorojo I  have still the issue on Android, but works on ios.

**Comment by WhidRubeld** [comment]
I have this problem on Android only. Adding the `hideWhenScrolling: false` property does not solve the problem

```
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.2.5",
    "@react-navigation/stack": "^6.0.11",
```

**Comment by ysnbyzli** [comment]
> I have this problem on Android only. Adding the `hideWhenScrolling: false` property does not solve the problem
> 
> ```
>     "@react-navigation/native": "^6.0.8",
>     "@react-navigation/native-stack": "^6.2.5",
>     "@react-navigation/stack": "^6.0.11",
> ```

Hi, I have the same problem. Did you solve the problem? 🙏🏻

**Comment by WhidRubeld** [comment]
> > I have this problem on Android only. Adding the `hideWhenScrolling: false` property does not solve the problem
> > ```
> >     "@react-navigation/native": "^6.0.8",
> >     "@react-navigation/native-stack": "^6.2.5",
> >     "@react-navigation/stack": "^6.0.11",
> > ```
> 
> Hi, I have the same problem. Did you solve the problem? 🙏🏻


No, I haven't found a way around this problem. So I temporarily worked around a search modal for Android...

**Comment by vbornand** [comment]
With expo-router 3.4.1 using:
@react-navigation/native: 6.1.9
@react-navigation/native-stack: 6.9.17

The issue is resolved

**Comment by sidorchukandrew** [comment]
It turns out there was an issue with `react-native-screens` [here](https://github.com/software-mansion/react-native-screens/pull/1883). Updating to `3.26.0` fixed it for me.

**Comment by ysnbyzli** [comment]
> It turns out there was an issue with `react-native-screens` [here](https://github.com/software-mansion/react-native-screens/pull/1883). Updating to `3.26.0` fixed it for me.

@sidorchukandrew Hi 👋🏻, I using react-native-navigation on my expo project. When use headerSearchBarOptions not showing search icon on screen header. As you said, when I change the react-native-screens version to 3.26.0, the application stays in the splash screen, which means it crashes. So I'm using the latest version but again the search function still doesn't work.

Thank you for your interest 🙏🏻

```js
"dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@reduxjs/toolkit": "^2.0.1",
    "@shopify/flash-list": "1.4.3",
    "expo": "~49.0.15",
    "expo-font": "~11.4.0",
    "expo-splash-screen": "~0.20.5",
    "expo-sqlite": "~11.3.3",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "^3.29.0",
    "react-redux": "^9.0.4"
  }
```

```js
useLayoutEffect(() => {
    navigation.setOptions({
      headerLargeTitle: true,
      headerSearchBarOptions: {
        inputType: "text",
        cancelButtonText: "İptal",
        tintColor: colors.primary,
        placeholder: "Ürün ara",
        onChangeText: (event) => {
          setSearch(event.nativeEvent.text);
        },
        onFocus: () => {
          setIsSearchFocused(true);
        },
        onBlur: () => {
          setIsSearchFocused(false);
        },
        hideWhenScrolling: false
      }
    });
  }, [navigation, colors]);
```

**Comment by Robert27** [comment]
> With expo-router 3.4.1 using: @react-navigation/native: 6.1.9 @react-navigation/native-stack: 6.9.17
> 
> The issue is resolved

For me it’s not, I have the same versions. While Android is fixed, it started to appear on iOS. Now search bar is not rendered on initial render somehow.

**Comment by WhidRubeld** [comment]
> With expo-router 3.4.1 using: @react-navigation/native: 6.1.9 @react-navigation/native-stack: 6.9.17
> 
> The issue is resolved

I doubt this is true. Because the problem lies in the native layer. Expo system relies on stable versions of libraries (mainly major outputs) from version to version of Expo SDK. Therefore, I think that it is worth waiting for the update along with the Expo SDK update to version 50. There will most likely already be support for React Navigation 7.

For now, I see as an alternative option to write a plugin for Expo, which will improve the work of the package.

**Comment by vbornand** [comment]
> Therefore, I think that it is worth waiting for the update along with the Expo SDK update to version 50

It is resolved with Expo 50 still in preview but should be released in a couple of weeks. As mentioned above the bug is in another library.

**Comment by Robert27** [comment]
No it’s definitely not resolved in expo sdk 50 and the latest versions of the libs.
I have a view with searchbar inside my tab bar and it is not rendering on the initial render on iOS.
But I agree with you that the bug is in another library.

**Comment by WhidRubeld** [comment]
> > Therefore, I think that it is worth waiting for the update along with the Expo SDK update to version 50
> 
> It is resolved with Expo 50 still in preview but should be released in a couple of weeks. As mentioned above the bug is in another library.

Is there a link to MR in react-native-screens to make sure that Expo 50 will merge the solution to the problem?

**Comment by WhidRubeld** [comment]
https://github.com/software-mansion/react-native-screens/issues/1906

**Comment by WhidRubeld** [comment]
https://github.com/software-mansion/react-native-screens/pull/1883

**Comment by Acetyld** [comment]
Lets keep it open, still present

**Comment by Faliszek** [comment]
Not sure if this helps to debug, but maybe someone find useful as workaround.

For me issue fixes itself if I remove `refreshing` and `onRefresh` prop from my FlatList.
My code looks more or less like this

```
  useLayoutEffect(() => {
    props.navigation.setOptions({
      headerSearchBarOptions: {
        hideWhenScrolling: false,
        inputType: "text",
        placeholder: "Search assets",
        onChangeText: (event) => {
          setSearchParams((params) => ({
            ...params,
            search: event.nativeEvent.text,
          }));
        },
      },
    });
  }, [props.navigation]);
```

Component:
```
 return (
    <FlatList
      // refreshing={loading}
      // onRefresh={() => loadAssets(searchParams)}
      contentInsetAdjustmentBehavior="automatic"
      data={list}
        ListFooterComponent={() => {
        if (!loading) return null;
        return (
          <View style={styles.loadingIndicator}>
            <ActivityIndicator size="large" />
          </View>
        );
      }
      // Rest of component ...
      }} 
     />
```

Here are my dependencies:

```
    "@react-navigation/native": "^6.1.15",
    "@react-navigation/native-stack": "^6.9.24",
    "expo": "~50.0.11",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.4",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0"
 ```
 
 Here are screen recordings 1) Without passing refreshing and onRefresh, 2) With refreshing and onRefresh
 I am guessing it is something with calculating changes on layout?
 
 

https://github.com/react-navigation/react-navigation/assets/19210348/43a5891e-840b-4bd1-9213-487fabdb4071
https://github.com/react-navigation/react-navigation/assets/19210348/1d48d7c4-3742-48fc-8bb1-c610637a4902

Let me know if there is anything I can provide to help it debug

**Comment by coofzilla** [comment]
For me, if I remove `FlatList` then the search bar will render initially; however, if I add the `FlatList` I have to scroll first for it to appear.

**Comment by Jbraneke** [comment]
PLEASE FIX THIS PROBLEM!!!!!!!!! I NEEED HELP

**Comment by marijang** [comment]
Yep, i m also trying to show and hide search bar but it is so buggy. When state change it says that i need to use useLayoutEffect....

can u add function for show/hide


  useLayoutEffect(() => {
    if(events.planner.events.length > 0) {
      navigation.setOptions({
        headerSearchBarOptions: {
          placeholder: 'Search...',
          hideWhenScrolling: false,
          tintColor: theme.colors.primary,
          textColor: theme.colors.text,
          hintTextColor: theme.colors.textLight,
          
          onSearchButtonPress: ({ nativeEvent }) => {
            console.log('Search submitted:', nativeEvent.text); // Handle search submission
          },
          onChangeText: (e) => setSearchQuery(e.nativeEvent.text),
        },
      });
    }
  }, [navigation, events.planner.events.length]);

**Comment by jmarsh24** [comment]
I'm also running into this issue. Are there any temporary workarounds? This issue has been open for a long while.

**Comment by marijang** [comment]
hm im thinking to set different route if there is records or not...

**Comment by alberalgo** [comment]
Using headerLargeTitle in screenOptions of a Stack.Navigator in iOS reproduce this wrong behaviour.
With any List component as root -> broken.
With any other component like a View -> correct
Not using headerLargeTitle -> correct
Any thoughts?

**Comment by jvegax** [comment]
Still facing same issue, on Android is not working

**Comment by kerimovok** [comment]
> Yep, i m also trying to show and hide search bar but it is so buggy. When state change it says that i need to use useLayoutEffect....
> 
> can u add function for show/hide
> 
> ```js
> useLayoutEffect(() => {
>     if(events.planner.events.length > 0) {
>       navigation.setOptions({
>         headerSearchBarOptions: {
>           placeholder: 'Search...',
>           hideWhenScrolling: false,
>           tintColor: theme.colors.primary,
>           textColor: theme.colors.text,
>           hintTextColor: theme.colors.textLight,
>           
>           onSearchButtonPress: ({ nativeEvent }) => {
>             console.log('Search submitted:', nativeEvent.text); // Handle search submission
>           },
>           onChangeText: (e) => setSearchQuery(e.nativeEvent.text),
>         },
>       });
>     }
>   }, [navigation, events.planner.events.length]);
> 
> `
> 
>   
> ```

This helped, just using `setOptions` instead of `<Stack.Screen options={...}/>`

**Comment by fredrikburmester** [comment]
I also still want a solution.

**Comment by kurucaner** [comment]
> It turns out there was an issue with `react-native-screens` [here](https://github.com/software-mansion/react-native-screens/pull/1883). Updating to `3.26.0` fixed it for me.

This solved the issue for me

**Comment by vladcos** [comment]
Experiencing it on Expo 51, had to set `hideWhenScrolling: false` as a workaround

**Comment by ipoogleduck** [comment]
I am still having this issue, only on android, with react native v0.74.5

**Comment by ipoogleduck** [comment]
Fixed the issue I was having on Android by using the isFocused hook `const isFocused = useIsFocused()`, and then only setting the headerSearchBarOptions when `isFocused` is true. Example:

```
React.useLayoutEffect(() => {
        if (isFocused) { // User must be on this tab when search icon is set, or else it won't show
            navigation.setOptions({
                headerSearchBarOptions: {
                    ...
                },
            })
        }
    }, [isFocused, navigation]);
```

Seems like the issue was due to me having multiple bottom tabs with search bars and lazy loading turned off. The headerSearchBarOptions would try to set when the screen was not actually visible, but would fail.

**Comment by kurucaner** [comment]
One workaround I found is using `useEffect` instead of `useLayoutEffect`, but I noticed that the search bar on `iOS` devices became unstable in that case. Therefore, even though it's not recommended, I had to conditionally call `useEffect` or `useLayoutEffect` based on the device type.

```
if (isIOS) {
  useLayoutEffect(() => {
    navigation.setOptions({
      headerSearchBarOptions: {
        hideWhenScrolling: false,
      }
    });

    return () => {
      debouncedSearch.cancel();
    };
  }, [search, language, debouncedSearch, navigation]);
} else {
  useEffect(() => {
    navigation.setOptions({
      headerSearchBarOptions: {
        hideWhenScrolling: false,
      }
    });
  }, []);
}
```

@homit-dalia
