### ISSUE TITLE
Mismatch between Javascript part and native part of reanimated (3.16.1 vs 3.10.0)

### ISSUE THREAD

**Issue by nicolas-goyon** [react-navigation/react-navigation#12227]
### Current behavior

Before changes, i've got a stack navigation working, however when trying to implement drawers instead of just stack, i've got a the following error : 
```
 ERROR  ReanimatedError: [Reanimated] Mismatch between JavaScript part and native part of Reanimated (3.16.1 vs 3.10.0).
    See `https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#mismatch-between-javascript-part-and-native-part-of-reanimated` for more details., js engine: hermes
```

The problematic file is `src/components/Menu.js`

### Expected behavior

Just trying to get the drawers working following : [https://reactnavigation.org/docs/drawer-based-navigation/](https://reactnavigation.org/docs/drawer-based-navigation/)

### Reproduction

https://github.com/nicolas-goyon/IWA-Project-Frontend/tree/Notifications

### Platform

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [x] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.18
| @react-navigation/bottom-tabs          |  not in use
| @react-navigation/drawer               | ^6.7.2
| @react-navigation/material-top-tabs    | not in use
| @react-navigation/stack                | ^6.4.1
| @react-navigation/native-stack         | not in use
| react-native-safe-area-context         | ^4.14.0
| react-native-screens                   | ^3.35.0
| react-native-gesture-handler           | ^2.20.2
| react-native-reanimated                | ^3.16.1
| react-native-tab-view                  | not in use
| react-native-pager-view                | not in use
| react-native                           | 0.74.5
| expo                                   | ~51.0.28
| node                                   | v20.18.0
| npm or yarn                            | 10.8.2

Executing the app via running `npx expo start --tunnel` 
Phone : 
- Redmi Note 11 Pro 5G 
- OS Version : `1.0.5.0 TKCEUOR`
- Android Version : `13 TKQ1.221114.001`

**Comment by Skwarek71830** [comment]
Had the same problem, running:
`npx expo start -c`
Solved it for me.

Source:
https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting/#mismatch-between-javascript-code-version-and-reanimated-babel-plugin-version

**Comment by PwntasticKev** [comment]
I got this error this morning when having to upgrade my expo SDK. (newest version SDK 52)

My issue was resolved by these steps: 

- `npm install expo@latest` --install latest version
- `npx expo install --fix` -- upgrades all dependencies 
- delete your node_modules folder 
- `npm i` --install the goods
- `expo start -c` --start expo and clean cache


The expo documentation can be found here: https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/

**Comment by AndreyEscobar** [comment]
I solve this error whit the comand:

npm install react-native-reanimated@3.16.1 --force

**Comment by rhahudson1** [comment]
Still nothing working for me. Anyone find a fix for this?

**Comment by oshilaRightS** [comment]
still nothing working for me. Any idea please? 
`"dependencies": {
    "@expo/metro-config": "^0.19.5",
    "@expo/vector-icons": "^14.0.2",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native/metro-config": "^0.76.3",
    "@react-navigation/bottom-tabs": "^7.0.0",
    "@react-navigation/drawer": "^7.0.0",
    "@react-navigation/native": "^7.0.0",
    "@react-navigation/stack": "^7.0.18",
    "@reduxjs/toolkit": "^2.4.0",
    "autoprefixer": "^10.4.20",
    "axios": "^1.7.9",
    "expo": "^52.0.21",
    "expo-blur": "~14.0.1",
    "expo-constants": "~17.0.3",
    "expo-font": "~13.0.1",
    "expo-haptics": "~14.0.0",
    "expo-linear-gradient": "~14.0.1",
    "expo-linking": "~7.0.3",
    "expo-router": "~4.0.7",
    "expo-splash-screen": "~0.29.12",
    "expo-status-bar": "~2.0.0",
    "expo-symbols": "~0.2.0",
    "expo-system-ui": "~4.0.3",
    "expo-web-browser": "~14.0.1",
    "nativewind": "^4.1.23",
    "postcss": "^8.4.49",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.5",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-pager-view": "^6.5.1",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.1.0",
    "react-native-svg": "15.8.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.12.5",
    "react-redux": "^9.1.2",
    "tailwindcss": "^3.4.16"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.3.12",
    "@types/react-test-renderer": "^18.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.2",
    "react-native-svg-transformer": "^1.5.0",
    "react-test-renderer": "18.3.1",
    "typescript": "^5.3.3"
  },`

**Comment by billomore** [comment]
for all monorepo users that tried everything and it still throws this error:

I have a pnpm monorepo, and there's a package for the shared RN code. I updated the `react-native-reanimated` dependency in all relevant `package.json`s, removed `pnpm-lock.yml` and `node_modules`, re-installed the deps, verified I only have the correct reanimated version in `pnpm-lock.yml` and in `node_modules`, cleared the `metro` cache - and still got the error.

Little did I know that `pnpm` installed the reanimated package in the shared package `node_modules` folder too, separately - and didn't update it despite the `package.json` had the correct version. Removing the package's `node_modules` and re-running `pnpm install` have solved the problem.
