### ISSUE TITLE
ScrollView Flickering on Screen Navigate / Scroll - React Native 0.76 + React Navigation 6/7

### ISSUE THREAD

**Issue by arjun9755** [react-navigation/react-navigation#12662]
### Current behavior

I’m using React Native version 0.76.0 along with React Navigation v6 and v7.

When I use a header from React Navigation and wrap my screen content inside a ScrollView, the screen starts flickering or blinking whenever I:

Click any button on the scree

https://github.com/user-attachments/assets/ccdfadae-bd56-41fe-a61a-ff2f32796898

n

Try to perform any copy/paste action

Trigger any screen update (like state change)

 "@react-navigation/native": "^7.1.6",
    "@react-navigation/native-stack": "^7.3.10",

### Expected behavior

The screen should not flicker or blink when clicking buttons, performing copy/paste actions, or scrolling inside a ScrollView with a visible header.

### Reproduction

nan

### Platform

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-drawer-layout             |
| react-native-tab-view                  |
| react-native-screens                   |
| react-native-safe-area-context         |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by arjun9755** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/stack`
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/drawer`
> * `@react-navigation/material-top-tabs`
> * `react-native-drawer-layout`
> * `react-native-tab-view`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `7.1.6`, latest: `7.1.14`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

yes

**Comment by RN-Nitin** [comment]
I am facing the same issue

**Comment by arjun9755** [comment]
> I am facing the same issue

Fixed device height using Dimensions and added ScrollView to support overflow content.

**Comment by arjun9755** [comment]
> I am facing the same issue

I tried this   ENV['RCT_NEW_ARCH_ENABLED'] = '0' and its stop flickering and working

**Comment by arjun9755** [comment]
I tried this   ENV['RCT_NEW_ARCH_ENABLED'] = '0' and its stop flickering and working

**Comment by Adel-Nasim** [comment]
You can fix the flickering issue with either of these workarounds:

1️⃣ Use `freezeOnBlur: true`

This prevents inactive screens from re-rendering and eliminates layout jumps.

Note: This applies to `createNativeStackNavigator` from `@react-navigation/native-stack`, not `createStackNavigator` from `@react-navigation/stack.`

```
import { createNativeStackNavigator } from '@react-navigation/native-stack';

const Stack = createNativeStackNavigator<NavigatorParamList>();

const AppStack = () => {
  return (
    <Stack.Navigator
      screenOptions={{
        freezeOnBlur: true, // Prevent layout jumping (flickering)
      }}>
      <Stack.Screen name="loginScreen" component={LoginScreen} />
    </Stack.Navigator>
  );
};

```
2️⃣ Set a fixed height on your wrapper screen component
By constraining the height, you can prevent unexpected layout recalculations:

```
import { Dimensions, View } from 'react-native';
const screenHeight = Dimensions.get('window').height;

<View style={{ height: screenHeight - 100 }}>
  {/* Your screen content */}
</View>
```

3️⃣ Remove the default React Navigation header and use a custom header
Sometimes the main flickering issue comes from the navigation header itself. You can disable it and provide your own custom header component:

```
<Stack.Screen
  name="sampleScreen"
  component={SampleScreen}
  options={{
    headerShown: false, // disable default header
    header: () => null, // remove header
  }}
/>
```


Then render your custom header directly inside your screen component.
✅ Tested on React Native 0.76 with React Navigation v6 & v7 — both methods resolved the flickering.

**Comment by harya72** [comment]
@Adel-Nasim I have tried the first method but still getting the flicker issue when i am pressing a button in the scrollview. I am getting this issue in iOS only. In android everything is working fine.

**Comment by Adel-Nasim** [comment]
> [@Adel-Nasim](https://github.com/Adel-Nasim) I have tried the first method but still getting the flicker issue when i am pressing a button in the scrollview. I am getting this issue in iOS only. In android everything is working fine.

Did you try using `createStackNavigator` from `@react-navigation/stack`? Does the issue still persist?

**Comment by yard2010** [comment]
Any update on this? I'm having the same issue with
```
"@react-navigation/bottom-tabs": "7.3.14",
"@react-navigation/drawer": "7.4.4",
"@react-navigation/native": "7.1.10",
"@react-navigation/native-stack": "7.3.14",
```
