### ISSUE TITLE
Screen mounting twice on iOS [Expo Ejected App]

### ISSUE THREAD

**Issue by jsappme** [react-navigation/react-navigation#2599]
I am using:

```
"expo": "^20.0.0",
 "react": "16.0.0-alpha.12",
 "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
 "react-navigation": "^1.0.0-beta.12",
```

My main.js is rendering like this:
```
render() {
    if ( this.props.authStore.logging ) {
      return( <AppLoading/> )
    }
    else {
      return( <FirstLaunchNavigation/> )
  }
```
and FirstLaunchNavigation.js:
```
const FirstLaunchStackNavigator = StackNavigator(
  {
    Onboarding: {
      screen: OnboardingScreen,
    },
  },
  {
    navigationOptions: () => ({
      header: null,
    }),
  }
);
export default FirstLaunchStackNavigator
```

**Comment by jsappme** [comment]
I tried with this very simple code and I am still getting the double mounting with iOS.

```
import React from "react";
import { StyleSheet, Text, View } from 'react-native';
import { StackNavigator } from 'react-navigation';
import { Constants } from 'expo';

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };
  render() {
    return <Text>Hello, Navigation!</Text>;
  }
}

const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
});

export default class App extends React.Component {
  render() {
    return (
      <View>
          <Text>Im App</Text>
          <SimpleApp />
        </View> 
    );
  }
}
```
anybody else?

I am using xcode 8.3.3

**Comment by jsappme** [comment]
I am getting this issue with the sample code from the expo documentation
![img_6070](https://user-images.githubusercontent.com/13439477/30516913-f76e5c3c-9b09-11e7-90e6-5033fc3225e1.PNG)

https://docs.expo.io/versions/latest/guides/routing-and-navigation.html

As you can see the same screen is mounted twice so there is a back button directly

```
import React from 'react';
import {
  Text,
  View,
} from 'react-native';

import {
  StackNavigator,
} from 'react-navigation';

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Home'
  };

  render() {
    return (
      <View style={{alignItems: 'center', justifyContent: 'center', flex: 1}}>
        <Text onPress={this._handlePress}>HomeScreen!</Text>
      </View>
    )
  }

  _handlePress = () => {
    this.props.navigation.navigate('Home');
  }
}

export default StackNavigator({
  Home: {
    screen: HomeScreen,
  },
});
```

**Comment by javidjamae** [comment]
Having the same issue.

**Comment by tomdye** [comment]
Having a similar issue with multiple mounts / unmounts

**Comment by jsappme** [comment]
is there a previous version that is actually working?

**Comment by tomdye** [comment]
I believe this is fixed for the `DrawerNavigator` at least in `beta12`

**Comment by faahmad** [comment]
+1

**Comment by guilhermepontes** [comment]
same

**Comment by rotembcohen** [comment]
This is the issue I'm experiencing in my own app on iOS. It was made with expo version 20:
https://drive.google.com/open?id=0B6g0TW_hcUL-Y08xZ3dnSlF0R3Y4T1d5WTFOaWxBZ001b1NF

**Comment by jsappme** [comment]
@rotembcohen same issue, thanks for posting this video

**Comment by javidjamae** [comment]
In case it helps anybody else, my issues was that I had nested navigators like this:

```
const MainTabNavigator = TabNavigator( {
  connectionList: {
    screen: ConnectionListNavigator,
    navigationOptions: {
      tabBarLabel: 'Connections',
      tabBarIcon: ( { tintColor } ) =>
        <Icon
          color= { tintColor }
          name="people"
          size={ 30 }
        />
    }
  },
  //...
} )

const MainNavigator = StackNavigator( {
  root: {
    screen: MainTabNavigator,
    navigationOptions: {
      header: null,
    },
  },
 // ...
} )

const AppNavigator = TabNavigator( {
  splashflow: { screen: SplashNavigator },
  auth: { screen: LoginScreen },
  main: { screen: MainNavigator }
}, {
  navigationOptions: {
    tabBarVisible: false
  },
  lazy: true,
} )
```

Then after authenticating, I was doing this, which caused it to mount the component on top of itself multiple times in the StackNavigator so I had to hit the back in the left nav multiple times to get back to the main one.
```
navigator.navigate( 'connectionList' )
```

When I switched it to this, the problem went away and it only showed the connectionList component once. 
```
navigator.navigate( 'main' )
```

In otherwords, telling it to load the connectionList was loading it multiple times, but telling it to load the main component and letting it figure out that it should show the connectionList based on it being the default option at each level worked fine. 

I'm not sure exactly why, but this solved my problem. 

Hope that helps others who may be experiencing this issue with nested navigators.

**Comment by jsappme** [comment]
I found a fix for my issue, I had to do something like this:

```
const DefaultStackNavigator = StackNavigator(
  {
    DefaultTabs: { screen: DefaultTabNavigator },
    Login: { screen: EntryScreen },
    Research: { screen: ResearchScreen },
    PropDetail: { screen: PropDetailScreen },
  },
  {
    initialRouteName:'DefaultTabs',
  }
);

const navigateOnce = (getStateForAction) => (action, state) => {
  const {type, routeName} = action;
  return (
    state &&
    type === NavigationActions.NAVIGATE &&
    routeName === state.routes[state.routes.length - 1].routeName
  ) ? null : getStateForAction(action, state);
};

OwnerStackNavigator.router.getStateForAction = navigateOnce(OwnerStackNavigator.router.getStateForAction);
```

**Comment by rotembcohen** [comment]
@jsappme can you elaborate? how would you solve the problem in the simple code you wrote in [this comment](https://github.com/react-community/react-navigation/issues/2599#issuecomment-329991853)? 
I am not using nested navigators, so I don't really understand how to implement your fix in my app.

This is my App.js:

```
import React from 'react';
import { StackNavigator } from 'react-navigation';

import WelcomeView from './containers/WelcomeView';
import LoginView from './containers/LoginView';
import HomeView from './containers/HomeView';
import GameView from './containers/GameView';
import RegistrationView from './containers/RegistrationView';

const App = StackNavigator({
    WelcomeView: {screen: WelcomeView},
    LoginView: {screen: LoginView},
    HomeView: {screen: HomeView},
    GameView: {screen: GameView},
    RegistrationView: {screen: RegistrationView}
},
{
    initialRouteName: 'WelcomeView',
    headerMode: 'none'
});

export default App;
```

**Comment by jsappme** [comment]
here is the fixed code:

```
import React from "react";
import { StyleSheet, Text, View } from 'react-native';
import { StackNavigator } from 'react-navigation';
import { Constants } from 'expo';

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };
  render() {
    return <Text>Hello, Navigation!</Text>;
  }
}

const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
});

const navigateOnce = (getStateForAction) => (action, state) => {
  const {type, routeName} = action;
  return (
    state &&
    type === NavigationActions.NAVIGATE &&
    routeName === state.routes[state.routes.length - 1].routeName
  ) ? null : getStateForAction(action, state);
};

SimpleApp.router.getStateForAction = navigateOnce(SimpleApp.router.getStateForAction);

export default class App extends React.Component {
  render() {
    return (
      <View>
          <Text>Im App</Text>
          <SimpleApp />
        </View> 
    );
  }
}
```

**Comment by Cygnus2112** [comment]
having same problem.

**Comment by windhost** [comment]
+1

**Comment by rotembcohen** [comment]
@jsappme your code is missing

`import { NavigationActions } from 'react-navigation';`

otherwise, worked well. thanks!!

**Comment by carsonwah** [comment]
+1

**Comment by Raveler** [comment]
+1, this is a very serious bug...

**Comment by carsonwah** [comment]
@jsappme Thanks for the workaround!

I haven't test it on standalone app yet. But for anyone coming here in the future, the most important part of the code is `routeName === state.routes[state.routes.length - 1].routeName`, which checks if the navigating new route is the same as the previous one.

Just a reminder, do not use this if your app has some logics like navigating to the same route.

**Comment by Raveler** [comment]
Hey guys! I have written a more streamlined version of the workaround by @jsappme. Just create a module from the following code and use it as a drop-in replacement for StackNavigator:

`
import { NavigationActions, StackNavigator } from 'react-navigation';

const navigateOnce = (getStateForAction) => (action, state) => {
  const {type, routeName} = action;
  return (
    state &&
    type === NavigationActions.NAVIGATE &&
    routeName === state.routes[state.routes.length - 1].routeName
  ) ? null : getStateForAction(action, state);
};

function BugFreeStackNavigator() {
	var navigator = StackNavigator.apply(null, arguments);
	navigator.router.getStateForAction = navigateOnce(navigator.router.getStateForAction);
	return navigator;
}

module.exports = BugFreeStackNavigator;

`

**Comment by AhadCove** [comment]
Could anyone explain why this happens on an ejected app?

**Comment by Thadeu** [comment]
+1 having same problem

**Comment by Thadeu** [comment]
@Raveler This solved my problem, but it is not definite.
Thanks

**Comment by nickyhajal** [comment]
I'm experiencing this exact issue with a detached Expo app running ExpoKit. Big thanks to @jsappme and @Raveler for their temporary fixes.

**Comment by msageryd** [comment]
Thank you @Raveler! Your solution helped me. 

I have a simple stack with three routes. After popping the last route I got an extra `componentWillMount()` fired which led to: 
**"Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component.."**

I included the above message for others to find via search. It would have helped me sooner. 

I don't actually understand the underlaying problem. But It became a problem in my app after upgrading from React-Navigation "1.0.0-beta.12" to "1.0.0-beta.17"

**Comment by kelset** [comment]
@msageryd 
> Anyone knows whats going on? This is too deep for me to try to dig into. I'm very grateful for the React-Navigation component, but at this stage its starting to feel a bit sketchy. Please tell me if someone needs more insight and I'll try to do some more/deeper logging.

Currently there's no easy answer to that, I'm sorry. Things are moving slowly on this side of the barricade too, but we are trying to still keep the lib up.

Btw can you do one more test by pointing to master instead of `beta.17`? The [latest two commits](https://github.com/react-community/react-navigation/commits/master) we merged are related to "low-level" behaviour 🤞

**Comment by msageryd** [comment]
@kelset `npm remove react-navigation && npm install react-navigation` got me version beta.21. The problem is still there, but it's not consistent. Often I can pop the route one time, but the next time it fails.

Any logging I can do to help?

**Comment by kelset** [comment]
@msageryd to point to master you need to write in your `package.json` as dep `"react-navigation": "react-community/react-navigation",` and then run npm.

**Comment by msageryd** [comment]
Ok, I did that now. But I'm unsure of what version I got. The package.json file in node_modules/react-navigation looks like this:
`"_id": "react-navigation@1.0.0-beta.21",`

**Comment by kelset** [comment]
yes the number is still beta.21 because we haven't released a new version ;) But the code should be updated to the latest commit; is the duplication still there?

**Comment by msageryd** [comment]
Yes, the issue remains. My app is quite large, so it would not be easy to break out a demo of the problem. But I'm all setup for deeper logging if you want.

**Comment by kelset** [comment]
I think it would be worth it, but I don't use Expo personally so I am not sure I'd be able to help.

cc @brentvatne @skevy this issue is more up your alley I think

**Comment by msageryd** [comment]
@kelset My app is not created in Expo.

**Comment by gregblass** [comment]
Just detached to Expokit and this started happening to me as well.

**Comment by byzyk** [comment]
I'm using deeply nested navigators in pair with Redux and have been finally able to overcome this with the following dirty fix:
```
export const nav = (state: any = initialState, action: any) => {
  const { type, routeName } = action;
  if (state && state.routes) {
    const { routes, index } = state;
    if (routes[index].routeName === routeName) {
      return state;
    }
  }
  return getStateForAction(action, state) || null;
};
```

**Comment by justinobney** [comment]
I am having the same issue.

`"react-navigation": "^1.0.0-beta.21",`

This does not happen while in the expo app, but it does once I build the stand-alone app.

**Comment by kelset** [comment]
Hey @justinobney, thanks for the hint of when this was introduced, this Jan hopefully there's going to be a higher number of hrs spent on this lib by some of the maintainers so (finger crossed) we'll be able to fix this - since it's quite a weird/complex/spread issue.

Morever actually having someone being able to "recreate" this bug without using Expo (@msageryd) should help scoping it.

**Comment by jevakallio** [comment]
@kelset @justinobney @msageryd I found the root cause and submitted a PR for a fix.

You can change the following in your package.json to test my branch:
```
"react-navigation": "jevakallio/react-navigation#fix/double-navigation-with-empty-initial-url"
```

**Comment by kelset** [comment]
Anyone with the issue can test and leave a comment on the PR that it fixes it for them? I'll test it on my app but I never managed to repro in the first place.

**Comment by jevakallio** [comment]
Fixes the issue in our app. Unfortunately can't share that repro, as the project is closed-source.

I could create a repro repo, but since ejected Expo apps are ~300MB heavy, feels like a waste of bytes given that this is easy to reproduce with e.g. the following code:
```
import React from 'react';
import { Text } from 'react-native';
import { StackNavigator } from 'react-navigation'; // 1.0.0-beta.22

export default StackNavigator({
  Home: { screen: () => <Text>Hello Navigation</Text> }
});
```

In an ejected Expo app, this will produce a stack navigator with the `Home` route duplicated on the route stack.

**Comment by brentvatne** [comment]
Fixed in https://github.com/react-navigation/react-navigation/commit/4373544257bcab7fa01aef8621ee74a0a83149ee and released in beta.23

**Comment by hlbp** [comment]
Wowww @Raveler that module did help me a lot! i thought for weeks i have  something wrong in my code. Thank you so much!!

**Comment by hlbp** [comment]
Wowww @Raveler that module did help me a lot! i thought for weeks i have  something wrong in my code. Thank you so much!!
