### ISSUE TITLE
DrawerNavigators as children of TabNavigators buggy on Android

### ISSUE THREAD

**Issue by XinHuaLuFang** [react-navigation/react-navigation#2743]
### Source code
[https://github.com/XinHuaLuFang/xhlf-react-navigation/blob/master/app/TabHaveSelfDrawer.js](https://github.com/XinHuaLuFang/xhlf-react-navigation/blob/master/app/TabHaveSelfDrawer.js)

### Current Behavior
* click button (OPEN HOME DRAWER) => just show a shade
* you can open drawer with gesture
* open drawer and click Home2 => screen show Home2 but drawer do not disappear

### Expected Behavior
* click button (OPEN HOME DRAWER) => show shade and drawer
* open drawer and click Home2 => screen show Home2 and drawer disappear

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.48.3
| node             | 6.11.2
| yarn      | 0.27.5

**Comment by kelset** [comment]
Hi @XinHuaLuFang thanks for reporting, can you try using the latest version? We fixed a lot of bugs related to the Drawer lately.

**Comment by XinHuaLuFang** [comment]
@kelset The latest version(beta.13) has the same bug.

**Comment by kelset** [comment]
Ok thanks for letting me know, we'll look into this.

**Comment by Gkjsdll** [comment]
This is still an issue with 1.0.0-beta.26

| software | version |
|----------|---------|
| react-navigation | 1.0.0-beta.26 |
| react-native | 0.50.0 |
| node | 9.3.0 |
| yarn |  1.3.2 |

**Comment by brentvatne** [comment]
Snack reproducing this: https://snack.expo.io/Sk6z1ZKLf
Worth noting that it works as expected on iOS in my tests

**Comment by Rob117** [comment]
@kelset Can confirm still an issue on the latest version.

**Comment by brentvatne** [comment]
moving this to umbrella issue

**Comment by aaronleo28** [comment]
@brentvatne please could you link the umbrella issue and also provide an update on this issue? still isn't resolved in v2.2.1

**Comment by brentvatne** [comment]
also I am aware that it’s not resolved and it’s not a priority so if you want to see it fixed soon you should submit a pr :)

**Comment by MsMayuaner** [comment]
It doesn't solve the problem.

**Comment by brentvatne** [comment]
conversation belongs in https://github.com/react-navigation/react-navigation/issues/4154. nobody is working on this right not and we'd love some help :)
