### ISSUE TITLE
DrawerNavigator contentOptions activeTintColor or inactiveTintColor not working with Image/Icon 

### ISSUE THREAD

**Issue by nitin0331** [react-navigation/react-navigation#3310]
![device-2018-01-19-093202](https://user-images.githubusercontent.com/2297146/35136097-78285602-fd07-11e7-8fe9-e878c86f491d.gif)
### Current Behavior
DrawerNavigator contentOptions activeTintColor or inactiveTintColor not working with Image/Icon
but work with Text (If you can see above image color not change when Home is selected from NavigationDrawer)

### Expected Behavior
DrawerNavigator contentOptions activeTintColor or inactiveTintColor working with both  Image/Icon
and Text  (Home icon should become white when selected from NavigationDrawer)

### Environment
Windows OS
react-navigation@1.0.0-beta.27
react-native-cli: 2.0.1
react-native: 0.51.0
node: 6.11.0
npm: 3.10.10
### Code
`const AppDrawerNavigation = DrawerNavigator({

              Home: {
                screen: HomeScreen,
                 navigationOptions: {
                  drawerLabel: 'Home',
                  drawerIcon: () => (
                    <Image
                      source={require('./src/images/rocket.png')}
                    />
                  ),
                  }
              },

              WebViews: {
                screen: WebViewScreen,
              },
              UserList: {
                screen: UserListScreen,
              },
              SwipeCard: {
                screen: SwipeCardScreen,
               },
            },
            {
             navigationOptions: {
              headerMode: 'none'
            },
            drawerPosition: 'left',
            drawerWidth: 200,
            contentOptions: {
              activeTintColor :'#ffffff',
               inactiveTintColor :'#1999CE',

              activeBackgroundColor :'#1999CE',
              inactiveBackgroundColor :'#ffffff',
            }
          }

          );`

I have also tried to add style inside image but its also not working 
style={[styles.icon,{ focused: true, color:'#ffffff', tintColor: '#1999CE' }]}

   ` drawerIcon: () => (
                    <Image
                      source={require('./src/images/rocket.png')}
                    style={[styles.icon,{ focused: true, color:'#ffffff', tintColor: '#1999CE' }]}

                    />
                  ),

`

**Comment by huangketong** [comment]
TabNavigator tabBarOptions activeTintColor or inactiveTintColor not working with Image
``` javascript
tabBarIcon: () => {
            return (<Image
                source={require('../../assets/tab_mine_icon_gray.png')} />
            )
        }
```

**Comment by huangketong** [comment]
My problem has been solved.
(tabBarIcon)[https://reactnavigation.org/docs/navigators/tab#tabBarIcon]
```
tabBarIcon: ({tintColor, focused}) => {
            return (<Image
                style={{tintColor: tintColor}}
                source={require('../../assets/tab_mine_icon_gray.png')} />
            )
        },
```
@nitin0331 You can try this way as me, I hope it will help you(drawerIcon)[https://reactnavigation.org/docs/navigators/drawer#drawerIcon]

**Comment by nitin0331** [comment]
@huangketong I have already tried with tintColor but its change the icon color completely even if its not selected.
I m assuming its a but in react-navigation as i have tried every possiblity to solve the issue but its still the same. 
@kelset  awating you reply with solution.

 Home: {
                screen: HomeScreen,
                 navigationOptions: {
                  drawerLabel: 'Home',
                  drawerIcon: ({ tintColor  }) => (
                    <Image
                      source = {require('./src/images/rocket.png')} 
                       style={[styles.icon ,{tintColor: '#ffffff'} ]}

                    />
                  ),
                  },
              },

**Comment by satya164** [comment]
You get the `tintColor` as an argument. You need to use that to set the `tintColor` for image instead of hardcoding it.

**Comment by andl-transdev** [comment]
I have the same issue in drawer version **5.12.5**.

"@react-navigation/drawer": "^5.12.5",
"@react-navigation/native": "^5.9.4",
"@react-navigation/stack": "^5.14.4",
 
    
When I'm trying to set an image as Icon I receive: _Element type is invalid_.
Ex: 
```
   <Drawer.Screen
          name={screenKeys.STACK_SETTINGS}
          component={Settings}
          options={{
            title: translations.menu_account,
            drawerIcon: ({size}) => {
              return (
                // <Icon name="menu" size={size} />
                <Image
                  source={require('../../assets/images/markers/pickup.png')}
                />
              );
            },
          }}
   />
```
![Screenshot_1620213441](https://user-images.githubusercontent.com/62099217/117133521-42abf080-ad9c-11eb-8e35-4be8a3f7d98f.png)

Does anybody have an workaround or a solution for this problem?

**Comment by andl-transdev** [comment]
The documentation says that you can set for **drawerIcon** a React.Node and I don't understand where is the problem.
<img width="995" alt="Screenshot 2021-05-05 at 12 24 27" src="https://user-images.githubusercontent.com/62099217/117134047-fa410280-ad9c-11eb-9b20-8640bd1643f6.png">
