### ISSUE TITLE
Android: headerRight and headerLeft images disappear when away from border

### ISSUE THREAD

**Issue by caltv** [react-navigation/react-navigation#3365]
### Current Behaviour

On Android: Images used in headerRight and headerLeft disappear when the "right" style is used to move it in from the border. On iOS it works correctly.

![a](https://user-images.githubusercontent.com/219204/35433954-384020b2-027d-11e8-911e-2e1c9b6a7f47.png)

```
static navigationOptions = ({ navigation }) => ({
    title: 'Home',
    headerRight: ( 
      <TouchableOpacity onPress={() => navigation.navigate( 'Info' )}>
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', }}>
          <Image
            style={styles.imageForButtonInfo}
            source={require('../img/info.png')}
          />
        </View>
      </TouchableOpacity>
    ),
    headerLeft: (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', }}>
        <Image
          style={styles.imageForHomeHeader}
          source={require('../img/home.png')}
        />
      </View>
    ),
    headerStyle: styles.header,
    headerTitleStyle: styles.headerTXT,

  });

```
Styles

```
header: {
    backgroundColor: 'black',
  },
  headerTXT: {
    alignSelf:'center',  
    fontFamily: 'SlatePro-Medium',
    fontSize: 22,  
    color: 'white',
    textAlign: 'center',
  },
  imageForButtonInfo: {
    width: 28, height: 28, 
    right: (Platform.OS === 'ios') ? 10 : 10,
    bottom: (Platform.OS === 'ios') ? 5: 0 
  },

```
### Expected Behavior

The image should not get cut off

### How to reproduce

Add a headerRight or headerLeft image and move it in with a "right" value 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.26
| react-native     | 0.46.4

**Comment by vonovak** [comment]
I do not think this is a bug on our side tbh.

**Comment by caltv** [comment]
It's a problem as it's impossible to make an interface that looks the same on iOS and Android. 

On Android the icons look far too close to the border

**Comment by vonovak** [comment]
@caltv as always, a reproduction would be very helpful (preferably on snack) since nobody else but you has the resources needed. (images end etc.). I'd also recommend using react-native vector icons instead of images, they are super easy to work with and look great.

**Comment by caltv** [comment]
> react-native vector icons instead of images

Do you have an example of these in use?

**Comment by vonovak** [comment]
there are some in https://github.com/oblador/react-native-vector-icons

In a couple of days I will be releasing a small lib to handle navbar icons in react navigation for you, so that you don't have to mess with the margins and hitSlops and etc. I know this doesn't help now, but just a heads up..

**Comment by ericvicenti** [comment]
For now this is something we won't have resources to fix. If you post an example snippet on Expo snack, we could look further into it. But as @vonovak said, you can also use margin/padding, which should behave consistently.

It would be awesome if if you can do more exploration and figure out exactly what is different between the platforms. Is it something wrong with the whole header? Or is it just the side items? Is this related to SafeAreaView? Does this affect all header content, or just `<Image>` when using the "right" style? Maybe this can be fixed with some small change to the styles in `Header.js`.

Lets re-open this issue when somebody does an in-depth investigation.

**Comment by vonovak** [comment]
@caltv I have pushed my work to GH but it's not on npm yet. https://github.com/vonovak/react-navigation-header-buttons there may be some breaking changes before I do so (eg renaming some props), please keep that in mind

**Comment by caltv** [comment]
Thanks will check it out!

**Comment by joelgetaction** [comment]
I'm seeing a similar bug - if I set `paddingRight` on a `headerRight` button then it doesn't work on Android - taps are not received by the app, but it works perfectly on iOS.  If I remove the `paddingRight`, then taps are still NOT received on Android, but it looks terrible on iOS (jammed up against the right edge).  Any ideas?  This definitely looks like a bug in react-navigation ...

Here's my sample code:
```
import { Entypo } from "@expo/vector-icons";
import { StyleSheet, TouchableOpacity } from "react-native";
import EStyleSheet from "react-native-extended-stylesheet";

...

headerRight: (
    <TouchableOpacity style={{ backgroundColor: "red" }} onPress={() => console.log("headerRight pressed")}>
      <Entypo name="menu" size={30} color={EStyleSheet.value("$colorTextInputPlaceholderText")} />
    </TouchableOpacity>
  ),
```
