### ISSUE TITLE
willBlur/didBlur not fired on initial StackNavigator screen

### ISSUE THREAD

**Issue by thebnich** [react-navigation/react-navigation#3446]
I have a minimal `StackNavigator` like so:
```
const Navigator = StackNavigator({
  First: { screen: FirstScreen },
  Second: { screen: SecondScreen },
});
```

In `FirstScreen`, I register listeners in `componentDidMount`:
```
componentDidMount() {
  this.props.navigation.addListener('willBlur', () => console.log('willBlur'));
  this.props.navigation.addListener('didBlur', () => console.log('didBlur'));
}
```

`FirstScreen` also has a `Button` that navigates to `SecondScreen` using:
```
this.navigate('Second');
```

When `SecondScreen` is pushed, neither `willBlur` nor `didBlur` are fired the first time I leave `FirstScreen`. If I navigate back and press it again, `willBlur` and `didBlur` are fired as expected thereafter.

Using `react-navigation` 1.0.0-beta.30 and `react-native` 0.52.0.

**Comment by brentvatne** [comment]
repro'd this in https://snack.expo.io/HJRB8twLM

**Comment by brentvatne** [comment]
fixed in #3448 and beta.31

**Comment by yarism** [comment]
Hmm, I am running 1.1.2 where this issue should be solved if I understand right but I am having this issue as well. The first time the screen is loaded, nothing fires. The second, third etc it works fine.

Anyone else having problems with this still?

**Comment by brentvatne** [comment]
can you update to latest @yarism? 1.4.0

if this is still happening, please open a new issue :) thanks!

**Comment by malikhzr** [comment]
Hi @brentvatne. I am facing the same issue. I use react-navigation: 3.3.2, react-native: 0.57.8, redux: 4.0.1.
When I go to same page second time only willFocus listener gets fired. It seems issue is still there?

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
