### ISSUE TITLE
Infinite loop with COMPLETE_TRANSITION

### ISSUE THREAD

**Issue by Soren-Knudsen** [react-navigation/react-navigation#3560]
### Current Behavior

After upgrading from `1.0.0-beta.29` to `1.1.1`, my app ends up in an infinite loop with `Navigation/COMPLETE_TRANSITION`. I've been working on `1.0.0-beta.29` for quite some time without any issues. I did some research to figure out when the error was introduced, and it seems to be in `v1.0.0-beta.30` and onwards.

My navigator reducer looks like this:

```javascript
export default function NavigatorReducer(state, action) {
  // Initial state
  if (!state) {
    return fromJS(AppNavigator.router.getStateForAction(action, state));
  }

  // Is this a navigation action that we should act upon?
  if (includes(NavigationActions, action.type)) {
    return fromJS(AppNavigator.router.getStateForAction(action, state.toJS()));
  }

  return state;
}
```

My project originates from the '[Pepperoni App Kit](https://github.com/futurice/pepperoni-app-kit)' where I make use of Immutable.js. I used the guide provided to upgrade `react-navigation` to `1.0.0-beta.29` without any issues.

### Expected Behavior

Not ending up in an infinite loop with `Navigation/COMPLETE_TRANSITION`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.1.1
| react-native     | 0.53.3
| node             | 8.4.0
| npm or yarn      | 1.3.2

**Comment by jamsch** [comment]
I do see quite a lot of COMPLETE_TRANSITION events occurring in my Redux log. Only one of those events in this screenshot actually modified the state (set isTransitioning on a nested route to false). I'm assuming it's something to do with a recursive call and having more nested routes may affect how many actions are dispatched.

![selection_019](https://user-images.githubusercontent.com/12927717/36454638-b4e24a44-1701-11e8-9eb5-5d43de8550e3.png)

**Comment by skdenmark** [comment]
That could also be the case for me!
Is that by design? If so, what is the workaround if I'm in the need for a nested structure?

**Comment by brentvatne** [comment]
hi there!

as per the issue template, we can only process issues that are bug reports with reproducible examples. if you can post an example project that reproduces this without any superfluous code, please open a new issue with it. thanks!

**Comment by msolomon** [comment]
I also ran into this. I have a similarly nested navigator structure.

This began happening as of 03fbd98ce4a49eab19bd9a46c2cd48da6325aa88: if I add that back, the problem disappears.

I've worked around the infinite loop by ignoring this event in my redux reducer:

```js
import { NavigationActions } from 'react-navigation'

const navReducer = (state, action) => {
  switch (action.type) {
    case NavigationActions.COMPLETE_TRANSITION:
      return state // work around infinite COMPLETE_TRANSITION loop
    default:
      let toAdd = AppNavigator.router.getStateForAction(action, state.toJS())
      if (toAdd != null) return state.merge(toAdd)
      else return state
    }
}
```

`COMPLETE_TRANSITION` still fires frequently with no apparent relation to any navigation, so it's not ideal, but it's a workaround anyway.

**Comment by stevenleeg** [comment]
Running into this issue as well. Pretty frustrating, as it seems to have appeared out of nowhere.

**Comment by stevenleeg** [comment]
Just to add a data point: I was running into this issue as well and @msolomon's workaround appears to have fixed the issue for me.

**Comment by brentvatne** [comment]
@ericvicenti / @Ashoat - can you guys investigate this?

**Comment by Soren-Knudsen** [comment]
@brentvatne: Just another data point, the issue went away when I removed Immutable.JS from the solution.

**Comment by Ashoat** [comment]
@stevenleeg, @msolomon, @jamsch - are you using Immutable.JS?

**Comment by stevenleeg** [comment]
@Ashoat I am, yes

**Comment by stevenleeg** [comment]
I'll double check on those when I get some free time to play around with it. In the meantime for those of you struggling with this issue: I was able to temporarily resolve things by reverting back to React Navigation `1.0.0-beta.29`.

**Comment by jamsch** [comment]
I'm using Immutable.JS, however only for handling some data in other reducers, not on the nav reducer.

**Comment by brentvatne** [comment]
hey folks, we really need a reproducible example here. nobody encountering the issue is using a standard react-navigation setup, you're all using redux / immutable and sharing a store with nav state as far as i can tell. i will close this but please create a new issue with a reproducible example on snack. thank you!

**Comment by Swahjak** [comment]
@brentvatne I'm having the same issue with https://github.com/futurice/pepperoni-app-kit after updating the dependencies. I'm not sure if this is what you mean by reproducible example, but this is the current state of my project in which the error occurs https://github.com/Swahjak/pepperoni-app-kit/tree/updated-dependencies.

Could it be related to the way the pepperoni enforces immutability in https://github.com/Swahjak/pepperoni-app-kit/blob/updated-dependencies/src/redux/reducer.js.

```js
import {Map, fromJS} from 'immutable';
import {loop, combineReducers} from 'redux-loop-symbol-ponyfill';
import NavigatorStateReducer from '../modules/navigator/NavigatorState';
import CounterStateReducer from '../modules/counter/CounterState';
import SessionStateReducer, {RESET_STATE} from '../modules/session/SessionState';
// ## Generator Reducer Imports

const reducers = {
  // Counter sample app state. This can be removed in a live application
  counter: CounterStateReducer,
  // ## Generator Reducers

  // Navigator states
  navigatorState: NavigatorStateReducer,

  session: SessionStateReducer

};

// initial state, accessor and mutator for supporting root-level
// immutable data with redux-loop reducer combinator
const immutableStateContainer = Map();
const getImmutable = (child, key) => child ? child.get(key) : void 0;
const setImmutable = (child, key, value) => child.set(key, value);

const namespacedReducer = combineReducers(
  reducers,
  immutableStateContainer,
  getImmutable,
  setImmutable
);

export default function mainReducer(state, action) {
  const [nextState, effects] = action.type === RESET_STATE
    ? namespacedReducer(action.payload, action)
    : namespacedReducer(state || void 0, action);

  // enforce the state is immutable
  return loop(fromJS(nextState), effects);
}
```

**Comment by jamsch** [comment]
Completely uninstalled and removed ImmutableJS from my project, and instead replaced my data structures with ES6 Maps and Sets however am still getting between 2-6 "COMPLETE_TRANSITION" Redux events after navigation. Is this intended?

**Comment by Swahjak** [comment]
I think I may have found the error(?) and a possible solution in the pepperoni case (but this might apply to all immutable states):

**Original**
```js

import {fromJS} from 'immutable';
import {NavigationActions} from 'react-navigation';
import includes from 'lodash/includes';

import AppNavigator from './Navigator';

export default function NavigatorReducer(state, action) {
  // Initial state
  if (!state) {
    return fromJS(AppNavigator.router.getStateForAction(action, state));
  }

  // Is this a navigation action that we should act upon?
  if (includes(NavigationActions, action.type)) {
    return fromJS(AppNavigator.router.getStateForAction(action, state.toJS()));
  }

  return state;
}
```

**Fixed**
```js

import {fromJS} from 'immutable';
import {NavigationActions} from 'react-navigation';
import includes from 'lodash/includes';

import AppNavigator from './Navigator';

export default function NavigatorReducer(state, action) {
  // Initial state
  if (!state) {
    return fromJS(AppNavigator.router.getStateForAction(action, state));
  }

  // Is this a navigation action that we should act upon?
  if (includes(NavigationActions, action.type)) {
    const oldState = state.toJS();
    const newState = AppNavigator.router.getStateForAction(action, state.toJS());
    return oldState === newState ? state : fromJS(newState);
  }

  return state;
}
```

The  ```return oldState === newState ? state : fromJS(newState);``` prevents the reducer from returning a ```new``` (but unchanged) state. This seems to fix the 'loop' with an immutable state (in the pepperoni-app-kit).

Additionally; make sure the middleware is applied correctly (using ```toJS()```):

```js
const navigatorMiddleware = createReactNavigationReduxMiddleware(
  'root',
  state => state.get('navigatorState').toJS()
);
```

**Comment by walker-ll** [comment]
It seems to happen in onTransitionEnd ().

**Comment by brentvatne** [comment]
@Swahjak - the best way to report bugs and get help on them is to post an app that reproduces the bug with a *minimal* amount of unrelated code. if someone can do this we can help here but maintainers don't have the time on this repo to dig in to issues and wade through lots of app-specific code :) do appreciate you sharing it nonetheless and i'm glad you were able to resolve your issue.

**Comment by alnorris** [comment]
I'm having the same problem, @Swahjak solution, unfortunately, didn't fix it. Only solution I found was to include this in the reducer to ignore all "COMPLETE_TRANSITION"

```if (action.type.includes('COMPLETE_TRANSITION')) return state;````

**Comment by fatfatson** [comment]
same problem!
I think that's because the library will check if there's a new state after every COMPLETE_TRANSITION and perform some check again.
when using immutable.js it will always return a new state, so that's the problem.
two way:
1.don't use immutable for nav state
2.ignore COMPLETE_TRANSITION earlier with returning the current state.
