### ISSUE TITLE
Unsupported top level event type "onGestureHandlerStateChange" dispatched with v3 and Expo SDK 31

### ISSUE THREAD

**Issue by outaTiME** [react-navigation/react-navigation#5208]
Hi guys,
Today I upgraded to RC3 of react-navigation v3 and I got the following error on Android when clicked over a drawer item.

<img width="903" alt="image" src="https://user-images.githubusercontent.com/140472/48009562-c2d53a80-e0fa-11e8-89b8-a61db6b3e9c7.png">

Note: if I dismiss the message the app still runs and the drawer action is executed.

On iOS works as expected, I follow the migration guide from here:

https://reactnavigation.org/blog/2018/11/01/react-navigation-3.0-rc.html

**Comment by outaTiME** [comment]
Maybe something related to:

https://github.com/expo/expo/issues/2600

**Comment by brentvatne** [comment]
does not repro: https://github.com/brentvatne/lol-react-navigation-5208

maybe you didn't update properly? create a new issue with a repro and i'm happy to investigate

**Comment by balthazar** [comment]
I'm experiencing the same issue on Android and I'm not using Expo.

I've tried to create a reprod using a clean repo with a simple drawer inside a switch navigator but it works fine. I'm going to investigate more but It seems [this commit](https://github.com/kmagiera/react-native-gesture-handler/commit/10f239de4b315c34e145f6edf32a3e34b97bc65f) is related to the issue, I saw `react-navigation-drawer` is still on version 1.0.4 of the gesture handler, which might be an issue?

I've followed the upgrade instructions closely and am on all the latest versions, but if you had any hint of a possible cause I would be really thankful!

**Comment by brentvatne** [comment]
@balthazar - that's just under devDependencies, it doesn't actually get installed when you consume the package. when you attempted to repro on an empty project did you use the same react-native version?

**Comment by balthazar** [comment]
@brentvatne Ah right, my bad.

Yes same versions with the same device:

react 16.6.3
react-native 0.57.7
react-native-gesture-handler 1.0.10
react-navigation 3.0.2

I tried to search for all occurrences of the old naming `topGestureHandlerStateChange` in my node modules just in case but didn't find anything. One thing I tried was to remove my gesture-handler dep completely and the build still worked (but I got the error), shouldn't that be impossible since it's referenced in the `settings.gradle`? Or maybe I have some android cache somewhere that kept the old one? I'm always running the packager using `--reset-cache` too but it might be another thing?

**Comment by dangjian** [comment]
> @balthazar im using the same pattern as you, importing `react-native-gesture-handler` in file who creates the app container (`createAppContainer`) solves the problem and even solves the following require cycle warning:
> 
> <img alt="image" width="558" src="https://user-images.githubusercontent.com/140472/49846816-e9e2f400-fdab-11e8-95cb-abb56bf880d0.png">
> 
> @brentvatne any advise? im using the last react-navigation version (3.0.8)
> 
> Thanks !!!

fixed the issue by importing the 'react-native-gesture-handler' module, but don't know why?

**Comment by dangjian** [comment]
@balthazar you are right, I deleted my comment. By my understanding, this is just a workaround, and hope it can be fixed in next release.

**Comment by sinhpn92** [comment]
Why this issue have been closed?
I have same issue with:
```"react-native-gesture-handler": "^1.0.15",
"react-navigation": "^3.1.0"
```

Did you resolve this issue @balthazar @dangjian ?

**Comment by brendandestefano** [comment]
I'm also still seeing this error. I put `import 'react-native-gesture-handler';` in my file that has `createAppContainer` but still seeing the error.

I'm using:
`
"react-navigation": "3.0.9",
"react-native-gesture-handler": "^1.0.12",
`

Any progress on this bug @balthazar @dangjian ?

**Comment by sinhpn92** [comment]
@brendandestefano I have downgraded `react-native-gesture-handler` to version `1.0.9`. Maybe latest version have bug. You can try with this.

**Comment by brendandestefano** [comment]
for anyone else wondering. downgrading `react-native-gesture-handler` to `1.0.9` fixed crash for me

**Comment by wbercx** [comment]
In my case, downgrading from `react-native-gesture-handler` version `1.0.15` to `1.0.14` worked.

**Comment by husnaingoldev** [comment]
in my case nothing worked 😄

**Comment by brentvatne** [comment]
latest version of expo and react-navigation work well together
