### ISSUE TITLE
TabBarBottom should hide when Keyboard is activated

### ISSUE THREAD

**Issue by RalfNieuwenhuizen** [react-navigation/react-navigation#618]
Currently, the TabBarBottom is placed above the keyboard when you are typing. 
Sometimes it is displayed, sometimes it is not even properly rendered, and a white block is displayed.
Expected behavior would be that the Bar would disappear when the Keyboard becomes active.

Wondering if there is an easy way to implement this in the current version of react-navigation?

**Comment by vikeri** [comment]
If I understand correctly this will be an issue for everyone using Android and the default react-native settings >=0.42.0 after this commit: https://github.com/facebook/react-native/commit/e3d4ace3ae46e3e4046e1ec5a201b92033deb24a

I ran into it after upgrading using `react-native-git-upgrade` which added `android:windowSoftInputMode="adjustResize"` to my AndroidManifest.xml

**Comment by Yadro** [comment]
fixed for me
`android:windowSoftInputMode="stateUnspecified|adjustResize"`

**Comment by YassineSc** [comment]
I changed this : `android:windowSoftInputMode="adjustResize">` to this : `android:windowSoftInputMode="stateUnspecified|adjustResize"` but it still goes in top of the keyboard !

**Comment by NetPumi2** [comment]
in RN 0.44 this ```android:windowSoftInputMode="adjustResize">``` stop work. Any another solution? 😢

**Comment by augustoabreu** [comment]
What can i do if i want to "hide" the tabbar (stateAlwaysHidden) in some cases when the keyboard shows up (common screens), but in other cases (chat screen) i want the behavior of "adjustResize"?

**Comment by mmalfertheiner** [comment]
Hi,

this `android:windowSoftInputMode="stateAlwaysHidden"` was not working for me. As a workaround I created a wrapper component for `TabBarBottom` that listens for Keyboard events.

```
import React from 'react'
import { Keyboard } from 'react-native'
import { TabBarBottom } from 'react-navigation'

class TabBarComponent extends React.PureComponent {

  constructor(props) {
    super(props)

    this.keyboardWillShow = this.keyboardWillShow.bind(this)
    this.keyboardWillHide = this.keyboardWillHide.bind(this)

    this.state = {
      isVisible: true
    }
  }

  componentWillMount() {
    this.keyboardWillShowSub = Keyboard.addListener('keyboardDidShow', this.keyboardWillShow)
    this.keyboardWillHideSub = Keyboard.addListener('keyboardDidHide', this.keyboardWillHide)
  }

  componentWillUnmount() {
    this.keyboardWillShowSub.remove()
    this.keyboardWillHideSub.remove()
  }

  keyboardWillShow = event => {
    this.setState({
      isVisible: false
    })
  }

  keyboardWillHide = event => {
    this.setState({
      isVisible: true
    })
  }

  render() {
    return this.state.isVisible ?
      return <TabBarBottom {...this.props} />
      :
      null
  }
}

export default TabBarComponent
```

And in the TabNavigator simply set the tabBarComponent.

```
import TabBarComponent from './TabBarComponent.js'

export default TabNavigator({
...
}, {
    initialRouteName: '...',
    tabBarComponent: TabBarComponent,
  })
```

**Comment by YassineSc** [comment]
Hey, how can I use this on this library [https://github.com/timomeh/react-native-material-bottom-navigation/issues/26](url)

**Comment by eflath** [comment]
The simplest solution I've found is to use [KeyboardAvoidingView](http://facebook.github.io/react-native/releases/0.42/docs/keyboardavoidingview.html#keyboardavoidingview) as the main View of any component that may present a keyboard.

**Comment by allpwrfulroot** [comment]
@mmalfertheiner The PR won't work anymore, but could it be updated? This would be a great solution :)

**Comment by rad182** [comment]
`android:windowSoftInputMode="stateAlwaysHidden|adjustPan"` worked for me.

**Comment by dalianmao22233** [comment]
@rad182  this method works for me! Thank you!

**Comment by mesbahsabur** [comment]
Had the same with TabBarTop component, mmalfertheiner's solution worked for me!

**Comment by jordanmkoncz** [comment]
I tried every possible `windowSoftInputMode` option and all the options besides the default `adjustResize` meant that when the keyboard was visible, I couldn't scroll down to the bottom of the screen.

I ended up using the solution posted by @mmalfertheiner instead (with `android:windowSoftInputMode="adjustResize"`), which means that when the keyboard is visible the TabBarBottom is hidden, but I can still scroll down to the bottom of the screen.

**Comment by danieloprado** [comment]
The solution provided by @mmalfertheiner loses all styles and effects on Android...

**Comment by jordanmkoncz** [comment]
@danieloprado are you using `TabBarBottom`? I used the solution posted by @mmalfertheiner with `TabBarBottom` (like he's using in his example code) and the tab bar behaves exactly as expected on Android, i.e. it behaves identical to how it does on iOS and does not lose all styles and effects. This is the configuration of my `TabNavigator`, perhaps you have something configured differently to me and that's what's causing your issues on Android?

```
export const MainTabNavigator = TabNavigator(
  {
    [SCREEN.CONTACTS_NAVIGATOR]: { screen: ContactsNavigator },
    [SCREEN.ALERTS_NAVIGATOR]: { screen: AlertsNavigator },
    [SCREEN.DASHBOARD_NAVIGATOR]: { screen: DashboardNavigator },
  },
  {
    tabBarComponent: TabBarBottomKeyboardAware,
    tabBarPosition: 'bottom',
    swipeEnabled: false,
    animationEnabled: false,
    tabBarOptions: {
      activeTintColor: COLOUR.FLAME,
      inactiveTintColor: COLOUR.BLACK,
      showLabel: false,
      showIcon: true,
    },
    navigationOptions: {
      header: null,
    },
  }
);
```

**Comment by danieloprado** [comment]
Original:
![original](https://user-images.githubusercontent.com/7683575/30640850-181c0582-9ddb-11e7-9af7-bf60fed559a7.gif)

After:
![after](https://user-images.githubusercontent.com/7683575/30640853-1c5e4010-9ddb-11e7-80c8-c8edb72c9545.gif)

Configuration:
![screenshot_20170920_081145](https://user-images.githubusercontent.com/7683575/30640924-680f713c-9ddb-11e7-935b-30205d48683f.png)

**Comment by jordanmkoncz** [comment]
Hmm, do you want to post your `TabBarComponent` code that you're using in the example above? I see what you mean about how some styles are not working correctly, but can't think of any reason why that would be happening. Please send the code itself rather than a screenshot of the code. :)

**Comment by danieloprado** [comment]
Same as @mmalfertheine, thanks for your help!

```js
import React from 'react'
import { Keyboard } from 'react-native'
import { TabBarBottom } from 'react-navigation'

class TabBarComponent extends React.PureComponent {

  constructor(props) {
    super(props)

    this.keyboardWillShow = this.keyboardWillShow.bind(this)
    this.keyboardWillHide = this.keyboardWillHide.bind(this)

    this.state = {
      isVisible: true
    }
  }

  componentWillMount() {
    this.keyboardWillShowSub = Keyboard.addListener('keyboardDidShow', this.keyboardWillShow)
    this.keyboardWillHideSub = Keyboard.addListener('keyboardDidHide', this.keyboardWillHide)
  }

  componentWillUnmount() {
    this.keyboardWillShowSub.remove()
    this.keyboardWillHideSub.remove()
  }

  keyboardWillShow = event => {
    this.setState({
      isVisible: false
    })
  }

  keyboardWillHide = event => {
    this.setState({
      isVisible: true
    })
  }

  render() {
    return this.state.isVisible ?
      <TabBarBottom {...this.props} />
      :
      null
  }
}

export default TabBarComponent
```

**Comment by jordanmkoncz** [comment]
@danieloprado looks like we'll have to wait for someone more experienced with react-navigation to comment. I can't see any obvious reason why you'd be losing some of the styles from wrapping `TabBarBottom` like this, so I assume the issue is due to the way those particular styles/animations are implemented relying on `TabBarBottom` being used directly rather than wrapped in another component.

**Comment by SupriyaKalghatgi** [comment]
Need a fix for this, waiting since long time

**Comment by vonovak** [comment]
this should be fixed in master through https://github.com/react-community/react-navigation/pull/1764

**Comment by NunoCardoso** [comment]
Hi all. I have this issue on Android. Expo SDK 24.0.2, attached app. It's still open, correct?

**Comment by SupriyaKalghatgi** [comment]
+1

**Comment by SupriyaKalghatgi** [comment]
Please reopen this issue

**Comment by PoliakovMaksym** [comment]
Since [#1764](https://github.com/react-navigation/react-navigation/pull/1764) got reverted and the issue is still present (with the @mmalfertheiner solution the `TabBarBottom` loses a lot of styles, especially animation effects) I am requesting to reopen this issue.

**Comment by satya164** [comment]
@danieloprado 's solution is the correct way to handle it. I'm not sure that it's possible to handle in the library in a decent way while addressing everyone's needs.

**Comment by JaxGit** [comment]
+1

**Comment by davebro** [comment]
As @mmalfertheiner and @dalianmao22233 have shown, their solutions work, so thank you! However, if you want your tabbar styles to persist, use TabBarTop and set tabBarPosition="bottom" instead of TabBarBottom. This is referenced here [https://github.com/react-navigation/react-navigation/issues/1739](url)

Instead of this

`render() {
    return this.state.isVisible ?
      <TabBarBottom {...this.props} />
      :
      null
  }`

Use this

`render() {
    return this.state.isVisible ?
      <TabBarTop tabBarPosition="bottom" {...this.props} />
      :
      null
  }`

And import at the top

`import { TabBarTop } from 'react-navigation'`

**Comment by brentvatne** [comment]
hi all, moving this issue over to react-navigation-tabs. thanks everyone for helping each other out here. https://github.com/react-navigation/react-navigation-tabs/issues/16
