### ISSUE TITLE
Memory leak in stack navigator

### ISSUE THREAD

**Issue by kaplantm** [react-navigation/react-navigation#7078]
### Current Behavior

- What code are you running and what is happening?
Android memory consumption is increasing as pages are pushed onto the stack, but memory is not release when navigation.popToTop or navigation.reset are used. Memory consumption increase is visible via `adb shell dumpsys meminfo [project]`. Memory increase can also be seen on device via system settings at a much less granular level. 

**Edit: this issue also occurs on iOS, see follow up comments**

### Expected Behavior

- What do you expect should be happening?
Memory should be released when stack is cleared using popToTop or reset.

### How to reproduce

I am able to see this issue using the example code from https://reactnavigation.org/docs/en/tab-based-navigation.html#a-stack-navigator-for-each-tab. I've also created a repo to demonstrate this based off that example: https://github.com/kaplantm/react-navigation-android-leak-example

I've provided the minimal example to see this issue, but in more complex apps, with enough pages pushed onto the stack (over 100, not at the same time - there are resets every 20 pages, so no more than 20 are mounted at a time) the app will eventually hit a memory limit.

### Your Environment
I've observed this happening while using react-navigation versions 2.18.3 (w/ react-native 0.57.7)  and 3.11.0 (w. react-native 0.59.9). 

| software         | version
| ---------------- | -------
| react-navigation |  3.11.0  or 2.18.3
| react-native     |  0.59.9 or 0.57.7
| node             |  8.11.4
| npm or yarn      |  npm 6.4.1

**Comment by ricardobeat** [comment]
Any updates on this? Seeing this exact issue. The `createStackNavigation` do not specify if screens are unmounted or not, while `createBottomTabNavigator` has a `lazy: true` for first render of tabs, plus `unmountOnBlur` to unmount them.

**Comment by zyslife** [comment]
I'm still using React -navigation in 1.6.1，I found that when I upgraded React -navigation to V5, I encountered a memory leak

**Comment by luatnd** [comment]
I see this issue on my app with react-navigation@3.x
As my investigation:
1. Open HomePage: 100MB
2. Open ArticleDetailPage: +30MB (130MB)
3. Back to HomePage: -20MB (120MB)
4. Open ArticleDetailPage: 130MB
5. Back to HomePage: 120MB
6. Open some other pages: Memory increases...

There was something ~20MB cached when you mounting a page, I think it relates to lazy-loading of the React components, when it was mounted to memory, it lives there until the app was kill & restarted.
Restart the JS thread do not release that memory.

Is this related to react-core + how we load our code? I don't have experience in native development so I cannot jump into a conclusion!

**Comment by LogunovAV** [comment]
Moving my suggestion from #7686 to this issue


We have a project where user can navigate through virtual artworks, each screen have lots of images and the design side implement a shortcut for search through it.

Our flow look like this: home -> search -> choose search result -> view result -> click shortcut for search -> search -> choose search result -> view result.

It looks like react-navigation doesn't clear if the same screen was open. We have tried to use each navigation method like direct navigation with navigator.navigate or pop screens.

Our data leaks rapidly going to gigabytes with this navigation flow which was unacceptable and we moved out from the react-navigation library and just implemented all the navigation with redux and big "if" statement in the app.js (which is ugly, but it works without any leaks)

update: 20.01.2021
It looks like react-navigation supports only finite automata for navigation, but if you have cycles in your navigation graph then it means you will be unavailable to use the library, am I right? This behavior should be documented in limitations or fixed in my opinion.

**Comment by rchristian** [comment]
I was also experiencing this issue. I've found a possible solution to import `enableScreens` from `react-native-screens` and call `enableScreens()` in my `App.js` component before my app (and, therefore, my Navigation component) renders.

**Comment by ducdh-fabbi** [comment]
I tried as @rchristian said, but it seems it only improves a litter, this is not the solution to solve this problem.

**Comment by abhaynpai** [comment]
Does any of you guys think this issue is related to https://github.com/software-mansion/react-native-screens/issues/843 ? 😕

**Comment by TNBoiBoi** [comment]
I'm having this bug too.
It's a severe problem please check it.

**Comment by williamswebworks** [comment]
Has there been any offical comments to this? I have the same issue with memory increasing when navigating the stack.

**Comment by LogunovAV** [comment]
I can help with an idea or a little bunch of the code if the team or significant developers from the team will give some feedback on it. 

It's hard to find the source of the issue in 3rd party code. It can take ages to find where required logic lays.

**Comment by Ahmed-Imam** [comment]
Any updates on this, I am still facing the same issue 
```
"react-native": "0.63.4",
"react-navigation": "^4.0.0",   
"react-navigation-material-bottom-tabs": "^1.0.0",   
"react-navigation-stack": "^2.10.4",   
"react-navigation-tabs": "^2.3.0",
```
But indeed enableScreens(false) removed the leak, but whats the tradeoff of doing that  ? 

![test](https://user-images.githubusercontent.com/20854551/115974453-68ace600-a58f-11eb-8e90-a595e32dd0b5.png)

**Comment by danieloi** [comment]
For me, enableScreens didn't do anything but I didn't see the memory leak in production mode. I'm in an expo managed app running SDK 40.

**Comment by vineethvijayan** [comment]
Facing similar issues but with tab bar navigation
I have 4 tabs, you log in and see the tabbar

- Switch to Screen 2, memory +100
- Switch to Screen 3, memory +100
- Switch to Screen 4, memory +100
- Switch to Screen 1, memory +100 then -80
- Switch to Screen 2, memory +100 then -80

_Memory size is representative only_

Like this, the memory will go beyond 1.7 GB and the app gets crashed.

**Comment by callaars** [comment]
This is an example for our app where we navigate to the same `Stack.Screen` with different parameters, same screen in, pop, in, pop, in, pop. Then you see in the end a sharp drop, which is when the app goes to the background, foreground, background, foreground.

As you can see there is never a real drop in memory, even if the screen isn't visible any more. I have `enableScreens` enabled and currently running the last versions.

https://user-images.githubusercontent.com/493348/127644181-0190eba9-57c0-4b29-846d-60e8591f0849.mov

**Comment by vineethvijayan** [comment]
Just wanted to confirm with @everyone, is this happening because of our code? or something from navigation?

We even tried with a simple flatlist, text and image. still the same scenario.

**Comment by The-Pr0grammer** [comment]
Nov 2021 : trying to solve this issue as we speak. If I find solution I will come back and post it

**Comment by java-james** [comment]
@The-Pr0grammer 👀 come to any conclusions on your dive in?

**Comment by The-Pr0grammer** [comment]
> @The-Pr0grammer 👀 come to any conclusions on your dive in?

After dissecting my app and learning much more about memory than I intended to, the solution end up being a simple change in syntax.

During my scrambling around the other day, trying to diagnose where my app was hemorrhaging memory, I had changed       

```
props.navigation.navigate('Profile');
```

to 

```
            //  props.navigation.reset({
            //     index: 0,
            //     key: null,
            //     routes: [{name: 'Profile'}],
            //   });
```

My intention behind using navigation.reset was to clear the stack navigator anytime one navigates to their profile page. Instead what appears to happen in my app is that the screen you are navigating FROM, holds onto the memory it is using and it is never freed up. This is so counter intuitive I still don't really understand why it works but after reverting back to the original way I had it 

```
props.navigation.navigate('Profile');
```

and using 

```
props.navigation.goBack('Home'); //<- I originally had this without the 'Home' screen name 
```

memory is now being released.

**Comment by The-Pr0grammer** [comment]
> @The-Pr0grammer 👀 come to any conclusions on your dive in?

After dissecting my app and learning much more about memory than I intended to, the solution end up being quite simple.

During my scrambling around the other day, trying to diagnose where my app was hemorrhaging memory, I had changed       

```
props.navigation.navigate('Profile');
```

to 

```
            //  props.navigation.reset({
            //     index: 0,
            //     key: null,
            //     routes: [{name: 'Profile'}],
            //   });
```

My intention behind using navigation.reset was to clear the stack navigator anytime one navigates to their profile page. Instead what appears to happen in my app is that the screen you are navigating FROM, holds onto the memory it is using and it is never freed up. This is so counter intuitive I still don't really understand why it works but after reverting back to the original way I had it 

```
props.navigation.navigate('Profile');
```

and using 

```
props.navigation.goBack('Home'); //<- I originally had this without the 'Home' screen name 
```

memory is now being released.

**Comment by java-james** [comment]
@The-Pr0grammer Interesting. Thanks for the update - Appreciate it! :)

**Comment by Hmoulvad** [comment]
> Facing similar issues but with tab bar navigation I have 4 tabs, you log in and see the tabbar
> 
> * Switch to Screen 2, memory +100
> * Switch to Screen 3, memory +100
> * Switch to Screen 4, memory +100
> * Switch to Screen 1, memory +100 then -80
> * Switch to Screen 2, memory +100 then -80
> 
> _Memory size is representative only_
> 
> Like this, the memory will go beyond 1.7 GB and the app gets crashed.

Anyone have an idea yet of how to fix this? I am having this exact same problem...

**Comment by yhrun** [comment]
> > @The-Pr0grammer 👀 come to any conclusions on your dive in?
> 
> After dissecting my app and learning much more about memory than I intended to, the solution end up being quite simple.
> 
> During my scrambling around the other day, trying to diagnose where my app was hemorrhaging memory, I had changed
> 
> ```
> props.navigation.navigate('Profile');
> ```
> 
> to
> 
> ```
>             //  props.navigation.reset({
>             //     index: 0,
>             //     key: null,
>             //     routes: [{name: 'Profile'}],
>             //   });
> ```
> 
> My intention behind using navigation.reset was to clear the stack navigator anytime one navigates to their profile page. Instead what appears to happen in my app is that the screen you are navigating FROM, holds onto the memory it is using and it is never freed up. This is so counter intuitive I still don't really understand why it works but after reverting back to the original way I had it
> 
> ```
> props.navigation.navigate('Profile');
> ```
> 
> and using
> 
> ```
> props.navigation.goBack('Home'); //<- I originally had this without the 'Home' screen name 
> ```
> 
> memory is now being released.
not work

**Comment by callaars** [comment]
Any update on this issue as on Android the performance gets abysmal.

**Comment by emagombe** [comment]
What a deception!!!
I didn't notice this when I started building my app. And now It is large with many features and I notice the memory leak problem.
This is not acceptable, the memory consumption hits more than 1 GB. This requires a serious review.
As till now there is no solution for this, I will move way from this library and use Redux to control my navigation!

**Comment by aJieBai** [comment]
Is there any solution? This is a serious problem

**Comment by waymond91** [comment]
Woah... Are there alternative navigation libraries?

**Comment by ahmetberkinc** [comment]
any update?

**Comment by arthurgeron-work** [comment]
> > @The-Pr0grammer 👀 come to any conclusions on your dive in?
> 
> After dissecting my app and learning much more about memory than I intended to, the solution end up being quite simple.
> 
> During my scrambling around the other day, trying to diagnose where my app was hemorrhaging memory, I had changed
> 
> ```
> props.navigation.navigate('Profile');
> ```
> 
> to
> 
> ```
>             //  props.navigation.reset({
>             //     index: 0,
>             //     key: null,
>             //     routes: [{name: 'Profile'}],
>             //   });
> ```
> 
> My intention behind using navigation.reset was to clear the stack navigator anytime one navigates to their profile page. Instead what appears to happen in my app is that the screen you are navigating FROM, holds onto the memory it is using and it is never freed up. This is so counter intuitive I still don't really understand why it works but after reverting back to the original way I had it
> 
> ```
> props.navigation.navigate('Profile');
> ```
> 
> and using
> 
> ```
> props.navigation.goBack('Home'); //<- I originally had this without the 'Home' screen name 
> ```
> 
> memory is now being released.

That's funny because internally react navigation's goBack method doesn't use/receive any parameters

**Comment by neegqi** [comment]
any update?

**Comment by waymond91** [comment]
In my case I had two different screens displaying maps.
One displayed a list of small maps as thumbnails, and once selected it navigates to a full screen map.
When the user deleted one of the map tiles the memory was reallocated correctly.
However when navigating in and out of the full screen map the tiles reload every time and memory from the previous  full screen map is not freed.
I expect in my case the map view is not being properly destroyed or unmourned…

**Comment by hbomatt** [comment]
> It's happening here with me. I have a stack with 2 screens. Going back and forth said screens piles up to 1.2 GB of RAM. I wasn't aware it was a problem until Android OS closes my RN app when using a gallery picker, probably due to _memory pressure_ and RN being in second plane.
> 
> Using `navigation.goBack()` or `navigation.pop()` does not free memory once the screen component is completely unmounted.
> 
> Package versions (partial packages.json):
> 
> ```json
> {
>   "dependencies": {
>     "@react-navigation/drawer": "^6.4.1",
>     "@react-navigation/native": "^6.0.10",
>     "@react-navigation/stack": "^6.2.2",
>     "react": "17.0.2",
>     "react-native": "0.68.2",
>     "react-native-animatable": "^1.3.3",
>     "react-native-gesture-handler": "^2.4.2",
>     "react-native-reanimated": "^2.8.0",
>     "react-native-safe-area-context": "^4.2.5",
>     "react-native-screens": "^3.13.1",
>     "react-native-svg": "^12.3.0"
>   }
> }
> ```

I'm also seeing this issue in recent package versions. I'll bump to the latest versions soon, to see if that helps, but I didn't see any release notes related to this problem. It's a severe problem for our app, unfortunately, with 1+ GB of memory consumption (that never seems to be freed)...

```
    "@react-navigation/bottom-tabs": "6.2.0",
    "@react-navigation/native": "6.0.8",
    "@react-navigation/stack": "6.1.1",
```

**Comment by emagombe** [comment]
Maybe this issue is related to this https://youtu.be/_xtXRnA-vEE

**Comment by nemzutkovic** [comment]
This is also reproducible in the examples provided in https://github.com/react-navigation/react-navigation/tree/main/example. In the [web example](https://react-navigation-example.netlify.com/), if you go to the "Bottom Tabs" and keep switching between the four tabs the JS heap keeps growing indefinitely. 

Here are screenshots, where I used Safari's web inspector to showcase 1GB of memory accumulates. Also, idling after all the navigation doesn't release much memory at all.

<img width="1792" alt="React-Navigation-Example 1GB" src="https://user-images.githubusercontent.com/29930888/208994968-6bfdaa56-8e97-4274-814e-053a6bd86e89.png">

**Comment by ABespolov** [comment]
Hey, guys! I have just fixed leak issue, it was related to some bugs in react-native-reanimated that is used in react native navigation package, for example: [this](https://github.com/software-mansion/react-native-reanimated/pull/3824). I have switched to latest version of reanimated library and leaks have gone!

I use this versions:

 "react-native": "0.70.6",
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/native-stack": "^6.9.7",
"react-native-reanimated": "https://github.com/software-mansion/react-native-reanimated.git#8209bfbbf368bec2a85cf34e8679c173574299cc"

**Comment by brianwx5** [comment]
does this also fix leaks in android as well?

**Comment by Ahmed-Imam** [comment]
Any updates on this issue ?? This has been on the radar for over three years and, sadly, there is no definitive solution yet. The user feedback about these crashes is growing, and it's become a real pain point. 

Despite flagging this issue during v4, it remains unresolved in v6. It's quite frustrating to encounter the same problem in the latest version that was present two years ago.

@satya164, @osdnk, @brentvatne, I'm a big fan of react-navigation and prefer not to switch.
 is there a solution for this or a reliable workaround ? Thanks for your attention to this matter.
 
 ```
   "react-native-screens": "^3.22.0",
   "@react-navigation/bottom-tabs": "^6.3.2",
   "@react-navigation/drawer": "^6.4.4",
   "@react-navigation/native": "^6.0.11",
   "@react-navigation/native-stack": "^6.7.0",
   "react-native-reanimated": "^3.3.0",
   "react-native-gesture-handler": "^2.12.0",
 ```

**Comment by Ahmed-Imam** [comment]
A fresh repo with memory leak on Android 
https://github.com/Ahmed-Imam/memoryLeak

**Comment by kesha-antonov** [comment]
Hi guys 🙌
Did anyone solve this? I use all latest versions of the libs but still have this issue on ios/android

**Comment by arthurgeron-work** [comment]
> Hi guys 🙌 Did anyone solve this? I use all latest versions of the libs but still have this issue on ios/android

As mentioned before, the source of the leak seems to be from reanimated, which is fixed in reanimated's V3+

**Comment by bbminhtri** [comment]
bump because we are facing the same issue. Will try to provide logs soon.

**Comment by ClementeSerrano** [comment]
Having the same issue here since a long time using React Navigation. Memory increases indefinitely, reaching GB of usages don't even navigating through the app. Read bad guys :/

**Comment by emagombe** [comment]
After analyzing this situation for a long time, here is my conclusion:

React Navigation is only responsible for clearing up the memory from the screen invoked. In case, you have a function or a native method that is called when the screen opens and causes a memory leak, React Navigation is not responsible for clearing that for you.

I'm saying that because I was building a music player app and I had a native method to load the artwork from the media files, but I was not clearing correctly the bitmap memory after loading. That way, when the list of music was called also with the method for each item of the list, the memory used to go higher. What you immediately expect is that when you hit the go back button the memory gets clear and when you load the screen again the memory goes higher, but that is not going to happen because React Navigation has nothing about my native allocations. Which also means if you are using any lib or any other thing that is causing the leak, you have to debug it your self and try to find out the reason of the leak.

Also, you can try creating a new app and only install React Navigation without any other lib and create screens and navigate, you will not notice any leak issues. The memory should vary from 50MB to 150MB max.
At least this was my experience about this, and I'm no longer having issues of memory leak on this.

Note: I'm just sharing my point of view based on my experiences, and I'm not saying that this is correct, as I'm not a maintainer/contributor of this lib.

Hope this helps someone!

**Comment by KartikBazzad** [comment]
When i am using navigation like this 
`import React, {useEffect} from 'react';
import {useAppSelector} from '../../redux/hooks';
import {getCurrentUser} from '../../redux/selectors';
import {View} from 'react-native';
import {Text} from 'react-native-paper';
import {useNavigation, StackActions } from '@react-navigation/native';
import {RootStackRoutes} from '../Router/routes';

export default function AuthLoading() {
  const currentUser = useAppSelector(getCurrentUser);
  const navigation: any = useNavigation();
  useEffect(() => {
    console.log(currentUser, navigation);
    if (currentUser) {
      navigation.dispatch(StackActions.dispatch(RootStackRoutes.App));
    } else {
     navigation.dispatch(StackActions.dispatch(RootStackRoutes.AuthStack));
    }
  }, [currentUser]);
  if (!currentUser) {
    return (
      <View>
        <Text style={{color: 'red'}}>Auth Loading</Text>
      </View>
    );
  }
  return null;
}
`

This gives  `Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)`


But when i use navigation.replace instead of using dispatch and StackActions it works perfectly fine
`import React, {useEffect} from 'react';
import {useAppSelector} from '../../redux/hooks';
import {getCurrentUser} from '../../redux/selectors';
import {View} from 'react-native';
import {Text} from 'react-native-paper';
import {useNavigation} from '@react-navigation/native';
import {RootStackRoutes} from '../Router/routes';

export default function AuthLoading() {
  const currentUser = useAppSelector(getCurrentUser);
  const navigation: any = useNavigation();
  useEffect(() => {
    console.log(currentUser, navigation);
    if (currentUser) {
      navigation.replace(RootStackRoutes.App);
    } else {
      navigation.replace(RootStackRoutes.AuthStack);
    }
  }, [currentUser]);
  if (!currentUser) {
    return (
      <View>
        <Text style={{color: 'red'}}>Auth Loading</Text>
      </View>
    );
  }
  return null;`

**Comment by mytabworks** [comment]
Deng they keep pushing a new version of this lib but haven't found a fix on a real serious problem... this lib is a good routing for rn starters but in the end of the road it is a trap.

**Comment by osdnk** [comment]
We empathize with @emagombe's comment as the lib is not responsible for cleaning the memory on the native side. 
The android leakage seems to be coming from another library... at least the provided traces suggest that the issue should be opened in another repository, @Ahmed-Imam ?

**Comment by efstathiosntonas** [comment]
Hey folks, since react-navigation uses `WeakMap` all over the place, in rn `0.73.5` they will merge this Hermes PR where it fixes some memory leaks on `WeakMap`: https://github.com/facebook/hermes/commit/e7b2abefabb6a9671e1d30d7af08cd1f32c9a670

more info: 

* https://github.com/facebook/react-native/issues/42620
* https://github.com/reactwg/react-native-releases/discussions/103#discussioncomment-8387628

Hopefully this mitigates the memory leaks.

**Comment by kesha-antonov** [comment]
> Hey folks, since react-navigation uses `WeakMap` all over the place, in rn `0.73.5` (probably releasing today as of 20 Feb 2024) they will merge this Hermes PR where it fixes a memory leak on `WeakMap`: https://github.com/facebook/hermes/commit/e7b2abefabb6a9671e1d30d7af08cd1f32c9a670
> 
> 
> 
> more info: 
> 
> 
> 
> * https://github.com/facebook/react-native/issues/42620
> 
> * https://github.com/reactwg/react-native-releases/discussions/103#discussioncomment-8387628
> 
> 
> 
> Hopefully this mitigates the memory leaks. 

Great news!

**Comment by hasanfd** [comment]
I tried with hermes `v0.73.5`, and its the same :( still seeing that images I created in the previous screen stays in the memory  even after navigation. One weird behaviour I realized is that hermes releases those memories if I lock the screen and unlock again :) I wish I can trigger this behaviour programmatically somehow

**Comment by emagombe** [comment]
> I tried with hermes `v0.73.5`, and its the same :( still seeing that images I created in the previous screen stays in the memory even after navigation. One weird behaviour I realized is that hermes releases those memories if I lock the screen and unlock again :) I wish I can trigger this behaviour programmatically somehow

Can you please share with us a reproduction repo?

**Comment by hasanfd** [comment]
> > I tried with hermes `v0.73.5`, and its the same :( still seeing that images I created in the previous screen stays in the memory even after navigation. One weird behaviour I realized is that hermes releases those memories if I lock the screen and unlock again :) I wish I can trigger this behaviour programmatically somehow
> 
> Can you please share with us a reproduction repo?

Sorry I don't have any. Its only happening in prod. 

Also, a correction: Memory management of `v0.73.5` is much better. Even though, it does not release the memory when I navigate to an another screen, it releases the memory after some time.

**Comment by Dmitrylolo** [comment]
I noticed this pattern: when you add more than one StackNavigator to BottomTabNavigator, there is a huge memory leak (Android)

**Comment by mobinni** [comment]
@Dmitrylolo You are definitely on to something here I was able to validate almost double the memory usage using stack navigators in the bottom tabs 😕

**Comment by emagombe** [comment]
> StackNavigator

You can only say that it's StackNavigator issue if when you remove the content of each component on your Tab.Screen leaving it empty and the issue remains.
If by leaving the component empty the issue does not remain, it means that it's not StackNavigator issue. You have to try to find out what is causing that leakage inside your Tab.Screen components.

As I mentioned above, StackNavigator is not responsible for clearing leakages caused by other libraries or codes when they are mounted when your screen opens.

> After analyzing this situation for a long time, here is my conclusion:
> 
> React Navigation is only responsible for clearing up the memory from the screen invoked. In case, you have a function or a native method that is called when the screen opens and causes a memory leak, React Navigation is not responsible for clearing that for you.
> 
> I'm saying that because I was building a music player app and I had a native method to load the artwork from the media files, but I was not clearing correctly the bitmap memory after loading. That way, when the list of music was called also with the method for each item of the list, the memory used to go higher. What you immediately expect is that when you hit the go back button the memory gets clear and when you load the screen again the memory goes higher, but that is not going to happen because React Navigation has nothing about my native allocations. Which also means if you are using any lib or any other thing that is causing the leak, you have to debug it your self and try to find out the reason of the leak.
> 
> Also, you can try creating a new app and only install React Navigation without any other lib and create screens and navigate, you will not notice any leak issues. The memory should vary from 50MB to 150MB max. At least this was my experience about this, and I'm no longer having issues of memory leak on this.
> 
> [Edit] So now you must be asking for self what memory does React Navigation cleans! React Navigation will clear only the memory held on the view. A certain list/amount of images, text, etc. has its amount of memory allocated on the view to allow it to be displayed. So that memory is supposed to be cleared by React Navigation.
> 
> Note: I'm just sharing my point of view based on my experiences, and I'm not saying that this is correct, as I'm not a maintainer/contributor of this lib.
> 
> Hope this helps someone!

**Comment by mobinni** [comment]
@emagombe Well the interesting thing is from my testing memory consumption only balloons in older Android versions. On 14 it remained stable regardless of using stacks inside the bottom tabs. On 11 it went up from 500mb to 800mb

**Comment by yunusemre** [comment]
Still relevant!
