### ISSUE TITLE
[Stack] The back animation get stuck on Android

### ISSUE THREAD

**Issue by ahce** [react-navigation/react-navigation#8126]
**Current Behavior**

- The back animation get stuck momentarily when navigation state is saved with [onStateChange](https://github.com/ahce/rn-navigation-stack-bug/blob/master/App.js#L35)

![rnnavbug](https://user-images.githubusercontent.com/12452003/80289706-5e52d480-870e-11ea-82ee-3c5f9e337750.gif)

**Expected Behavior**

- Fluid back animation

**How to reproduce**

- Clone this [repo](https://github.com/ahce/rn-navigation-stack-bug)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android 9
| @react-navigation/native       | 5.1.6
| @react-navigation/stack        | 5.2.13
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.7.0
| react-native                   | 0.62.2
| node                           | 12.16.2
| npm or yarn                    | yarn

**Comment by AwanesowArtem** [comment]
same issue

**Comment by satya164** [comment]
Don't perform state updates in `onStateChange`. It's intended for use cases such as side effects like persisting state, screen tracking etc.

**Comment by ahce** [comment]
> Don't perform state updates in `onStateChange`. It's intended for use cases such as side effects like persisting state, screen tracking etc.

@satya164  Thanks for your reply!

The bug also happens when called setOptions in focus effect.
Please check the repo again.
I have updated the code and the issue description.

**Comment by satya164** [comment]
The same principle applies. Don't do state-update/re-render during animations or it'll interrupt the animation. You can delay state updates until the animation finishes: https://reactnavigation.org/docs/use-focus-effect/#delaying-effect-until-transition-finishes

**Comment by ahce** [comment]
> The same principle applies. Don't do state-update/re-render during animations or it'll interrupt the animation. You can delay state updates until the animation finishes: https://reactnavigation.org/docs/use-focus-effect/#delaying-effect-until-transition-finishes

@satya164 I understand the principle, but it is strange that it only happens with animation SlideFromRightIOS. 
Also in v4, i don't have this problem with the same animation.

**Comment by marvinPlasmatic** [comment]
The problem still persists, I have the same problem, and even tested without doing any state updates or re-render during the animation.

**Comment by Jeepeng** [comment]
same here

**Comment by Razorholt** [comment]
same problem

**Comment by raajnadar** [comment]
Solution for the issue is already given.
