### ISSUE TITLE
Unable to resolve "./NavigationNativeContainer" from "node_modules/@react-navigation/native/src/index.tsx"

### ISSUE THREAD

**Issue by soulsako** [react-navigation/react-navigation#8163]
I am using managed Expo SDK 37 app with React Navigation 5.

When I run expo start -c, i get this the error:

`Unable to resolve "./NavigationNativeContainer" from "node_modules/@react-navigation/native/src/index.tsx"`

My package.json dependencies:

```
"dependencies": {
    "@expo/vector-icons": "^10.0.6",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/native": "^5.2.1",
    "@react-navigation/stack": "^5.2.16",
    "expo": "~37.0.3",
    "expo-asset": "^8.1.4",
    "expo-constants": "~9.0.0",
    "expo-font": "^8.1.1",
    "expo-permissions": "~8.1.0",
    "prop-types": "^15.7.2",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-web": "~0.11.7",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0"
  },
```

**Comment by joeyscarim** [comment]
same issue in a react native cli project i started today

**Comment by nhatnam99132** [comment]
same issue in a react native expo project i started today

**Comment by raajnadar** [comment]
Try `import { NavigationContainer } from '@react-navigation/native'

**Comment by shailu26** [comment]
what is this error?
its frustrating

**Comment by Karthik-B-06** [comment]
Updating @react-navigation/native library to the latest caused this problem to me.

**Comment by shailu26** [comment]
what version should we use?

**Comment by kristjanm** [comment]
I fixed (temporarily) by installing a bit older version:
npm install @react-navigation/native@5.1.7

I guess will be fixed by someone very soon

**Comment by shailu26** [comment]
what version you are using for this  "@react-navigation/drawer", @react-navigation/stack

**Comment by Charis-W** [comment]
1. rm -rf node_modules package-lock.lock
2. npm cache clean --force
3. npm install

**Comment by shailu26** [comment]
> I fixed (temporarily) by installing a bit older version:
> npm install @react-navigation/native@5.1.7
> 
> I guess will be fixed by someone very soon

fixed that issue

**Comment by Karthik-B-06** [comment]
The latest version of @react-navigation/bottom-tabs also has an issue.

**Comment by raajnadar** [comment]
Try this

1. Upgrade to latest version
2. Delete the lock file (yarn.lock or package.lock)
3. Clear the cache `yarn cache clean` or `npm cache clean`
4. Run `yarn` or `npm install`
5. Run `npx react-native run-android --reset-cache`

**Comment by kristjanm** [comment]
Got the latest version working with instructions here: https://reactnavigation.org/docs/troubleshooting/ (saved this link for future).

**Comment by soulsako** [comment]
> > I fixed (temporarily) by installing a bit older version:
> > npm install @react-navigation/native@5.1.7
> > I guess will be fixed by someone very soon
> 
> fixed that issue



> I fixed (temporarily) by installing a bit older version:
> npm install @react-navigation/native@5.1.7
> 
> I guess will be fixed by someone very soon

Downgrading to @react-navigation/native@5.1.7 still hasn't fix the issue

**Comment by stormbreaker1206** [comment]
thanks kristjanm this help me

**Comment by jamesdarabi** [comment]
> Got the latest version working with instructions here: https://reactnavigation.org/docs/troubleshooting/ (saved this link for future).

This worked for me after I updated to the latest version of `expo-cli`.

**Comment by RockyStrongo** [comment]
> Got the latest version working with instructions here: https://reactnavigation.org/docs/troubleshooting/ (saved this link for future).

Thanks for sharing this page!
running expo start -c fixed the issue for me

**Comment by davisgreg1** [comment]
Yes, running `expo start -c` worked for me.

**Comment by itsusmanmirza** [comment]
Today after updating @react-navigation/native and got this error too.
Tried downgrading to @react-navigation/native@5.1.7 = failed
Also tried Troubleshooting steps from [https://reactnavigation.org/docs/troubleshooting/](React Navigation Troubleshooting) = failed

So in the last what I did, go to **_"node_modules\@react-navigation\native\src\index.tsx"_** inside it, delete this below line, and rewrite it again using intellisense.
**export { default as NavigationContainer} from './NavigationContainer';**

And this worked for me. I don't even know how it worked but it does.
I hope it helps others.

**Comment by itsusmanmirza** [comment]
Today after updating **@react-navigation/native** and got this error too.
Tried downgrading to **@react-navigation/native@5.1.7** = **failed**
Also tried Troubleshooting steps from _https://reactnavigation.org/docs/troubleshooting/_ = **failed**

So in last what I did, go to -> _**"node_modules@react-navigation\native\src\index.tsx"**_ inside it, delete this line below, and rewrite it again using intellisense.
_**export { default as NavigationContainer} from './NavigationContainer';**_

And this worked for me. I don't even know how it worked but it does.
I hope it helps others too.

**Comment by itsusmanmirza** [comment]
> Today after updating **@react-navigation/native** and got this error too.
> Tried downgrading to **@react-navigation/native@5.1.7** = **failed**
> Also tried Troubleshooting steps from _https://reactnavigation.org/docs/troubleshooting/_ = **failed**
> 
> So in last what I did, go to -> _**"node_modules@react-navigation\native\src\index.tsx"**_ inside it, delete this line below, and rewrite it again using intellisense.
>` export { default as NavigationContainer} from './NavigationContainer';`
> 
> Also run with `expo start -c`
> And this worked for me. I don't even know how it worked but it does.
> I hope it helps others too.

**Comment by itsusmanmirza** [comment]
Today after updating **@react-navigation/native** and got this error too.
Tried downgrading to **@react-navigation/native@5.1.7** = **failed**
Also tried Troubleshooting steps from _https://reactnavigation.org/docs/troubleshooting/_ = **failed**
 
So in last what I did, go to -> _**"node_modules@react-navigation\native\src\index.tsx"**_ inside it, delete this line below, and rewrite it again using intellisense.
` export { default as NavigationContainer} from './NavigationContainer';`
 
Also run with `expo start -c`
And this worked for me. I don't even know how it worked but it does.
I hope it helps others too.

**Comment by raajnadar** [comment]
I will lock this because we already have a lot of solution for this issue.
