### ISSUE TITLE
TypeError: Cannot read property 'Provider' of undefined

### ISSUE THREAD

**Issue by Charis-W** [react-navigation/react-navigation#8166]
@react-navigation/bottom-tabs
**my code(app.js):**
import * as React from 'react';
import { Text, View } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

function HomeScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Home!</Text>
    </View>
  );
}

function SettingsScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Settings!</Text>
    </View>
  );
}

const Tab = createBottomTabNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomeScreen} />
        <Tab.Screen name="Settings" component={SettingsScreen} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}
**my package.json dependencies:**
{
  "name": "react_native_hooks",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.3.1",
    "@react-navigation/native": "^5.1.6",
    "@react-navigation/stack": "^5.2.14",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.4.0",
    "eslint": "^6.8.0",
    "jest": "^25.4.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
platform: ios/iPhone 11
**error**
![Simulator Screen Shot - iPhone 11 
TypeError: undefined is not an object (evaluating '_native.NavigationHelpersContext.Provider')
This error is located at:
    in BottomTabView (at createBottomTabNavigator.tsx:41)
    in BottomTabNavigator (at NavigatorExample2.js:27)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:281)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:39)
    in ThemeProvider (at NavigationContainer.tsx:38)
    in ForwardRef(NavigationContainer) (at NavigatorExample2.js:26)
    in BottomTabNavigators (at App.js:17)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in ForwardRef(SafeAreaView) (at App.js:15)
    in RCTView (at App.js:13)
    in App (at renderApplication.js:45)
    in RCTView (at AppContainer.js:109)
    in RCTView (at AppContainer.js:135)
    in AppContainer (at renderApplication.js:39)

render
    BottomTabView.tsx:103:32
finishClassComponent
    ReactNativeRenderer-dev.js:13591:30
updateClassComponent
    ReactNativeRenderer-dev.js:13516:23
beginWork$1
    ReactNativeRenderer-dev.js:15881:13
invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:286:9
invokeGuardedCallback
    ReactNativeRenderer-dev.js:497:30
beginWork$$1
    ReactNativeRenderer-dev.js:22028:6
performUnitOfWork
    ReactNativeRenderer-dev.js:20871:11
workLoopSync
    ReactNativeRenderer-dev.js:20848:21
performSyncWorkOnRoot
    ReactNativeRenderer-dev.js:20456:10

**Comment by Charis-W** [comment]
> @react-navigation/bottom-tabs
> This error is located at:
> in BottomTabView (at createBottomTabNavigator.tsx:41)
> in BottomTabNavigator (at NavigatorExample2.js:27)
> in EnsureSingleNavigator (at BaseNavigationContainer.tsx:281)
> in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:39)
> in ThemeProvider (at NavigationContainer.tsx:38)
> in ForwardRef(NavigationContainer) (at NavigatorExample2.js:26)
> in BottomTabNavigators (at App.js:17)
> in RCTSafeAreaView (at SafeAreaView.js:51)
> in ForwardRef(SafeAreaView) (at App.js:15)
> in RCTView (at App.js:13)
> in App (at renderApplication.js:45)
> in RCTView (at AppContainer.js:109)
> in RCTView (at AppContainer.js:135)
> in AppContainer (at renderApplication.js:39)
> 
> render
> BottomTabView.tsx:103:32
> finishClassComponent
> ReactNativeRenderer-dev.js:13591:30
> updateClassComponent
> ReactNativeRenderer-dev.js:13516:23
> beginWork$1
> ReactNativeRenderer-dev.js:15881:13
> invokeGuardedCallbackImpl
> ReactNativeRenderer-dev.js:286:9
> invokeGuardedCallback
> ReactNativeRenderer-dev.js:497:30
> beginWork$$1
> ReactNativeRenderer-dev.js:22028:6
> performUnitOfWork
> ReactNativeRenderer-dev.js:20871:11
> workLoopSync
> ReactNativeRenderer-dev.js:20848:21
> performSyncWorkOnRoot
> ReactNativeRenderer-dev.js:20456:10



> Hey! Thanks for opening the issue. Can you provide more information about the issue? Please fill the issue template when opening the issue without deleting any section. We need all the information we can to be able to help. Make sure to at least provide - Current behaviour, Expected behaviour, A way to [reproduce the issue with minimal code](https://stackoverflow.com/help/minimal-reproducible-example) (link to [snack.expo.io](https://snack.expo.io)) or a repo on GitHub, and the information about your environment (such as the platform of the device, exact versions of all the packages mentioned in the template etc.).

Yes, I've re edited the comments

**Comment by TriPSs** [comment]
@Charis-W I had the same issue, make sure you are using the latest version of `@react-navigation/native`

**Comment by JorgeLoaiza12** [comment]
> @Charis-W I had the same issue, make sure you are using the latest version of `@react-navigation/native`

I had the same problem, update to the latest version and it worked. Thank you!

**Comment by Charis-W** [comment]
> @Charis-W I had the same issue, make sure you are using the latest version of `@react-navigation/native`

Thanks for your help,it worked

**Comment by raajnadar** [comment]
It seems like the issue is resolved so I am closing this issue.

**Comment by kvlknctk** [comment]
I had some issue. I updated package.json. Like this. 
`"dependencies": {
    "@react-navigation/bottom-tabs": "^5.3.1",
    "@react-navigation/native": "^5.2.1",
    "@react-navigation/stack": "^5.2.16",
  },`

<img width="295" alt="Ekran Resmi 2020-05-01 14 39 59" src="https://user-images.githubusercontent.com/10873815/80803016-b16ad280-8bb9-11ea-8720-6da0b047866f.png">

But I am getting an error.

**Comment by stormbreaker1206** [comment]
i am having the same issue is this error fixed?

**Comment by kvlknctk** [comment]
> i am having the same issue is this error fixed?

Yes, there is no problem after update.

**Comment by nadavpld** [comment]
Same problem, Updated following to the latest version :

    "@react-navigation/drawer": "^5.6.3",
    "@react-navigation/material-top-tabs": "^5.1.14",
    "@react-navigation/native": "^5.2.3",
    "@react-navigation/stack": "^5.2.18",

deleted node_modules and installed again.

Problem still occurs.

> Unable to resolve module `./NavigationNativeContainer` from `node_modules\@react-navigation\native\src\index.tsx`

**Comment by krile136** [comment]
I have same error, but I don't know how to upgrade `@react-navigation/native` to latest version.
My project made by expo managed flow, please let me know how to upgrade.

my package.json

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.3.3",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "axios": "^0.19.2",
    "expo": "^37.0.0",
    "expo-constants": "~9.0.0",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-web": "^0.11.7",
    "react-native-webview": "8.1.1",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8"
  },
  "devDependencies": {
    "babel-preset-expo": "^8.1.0",
    "@babel/core": "^7.0.0"
  },
  "private": true
}

**Comment by seven7hell** [comment]
Below command will upgrade
`expo install @react-navigation/native`

**Comment by krile136** [comment]
@seven7hell 
> Below command will upgrade
expo install @react-navigation/native

Thank you ! I was able to upgrade react-navigation to latest  and  re-installed using yarn , it worked!

**Comment by MichaelGorski** [comment]
I have the same issue using expo, I deleted and installed everything again, doesn't work for me. =/

`undefined is not an object (evaluating '_native.NavigationHelpersContext.Provider')
- node_modules\@react-navigation\stack\src\views\Stack\StackView.tsx:423:25 in render
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:13042:21 in finishClassComponent
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:12970:4 in updateClassComponent
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:307:15 in invokeGuardedCallbackImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:531:36 in invokeGuardedCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:20488:8 in beginWork$$1
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19370:24 in performUnitOfWork
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19347:39 in workLoopSync  
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18997:22 in renderRoot    
* [native code]:null in renderRoot
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18709:28 in runRootCallback
* [native code]:null in runRootCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5642:32 in runWithPriority$argument_1
- node_modules\react-native\node_modules\scheduler\cjs\scheduler.development.js:643:23 in unstable_runWithPriority  
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5638:22 in flushSyncCallbackQueueImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5627:28 in flushSyncCallbackQueue
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18556:30 in scheduleUpdateOnFiber
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:11484:17 in dispatchAction* [native code]:null in dispatchAction
* App.js:51:4 in loadResourcesAndDataAsync
- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
- node_modules\regenerator-runtime\runtime.js:274:30 in invoke
- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
- node_modules\regenerator-runtime\runtime.js:135:28 in invoke
- node_modules\regenerator-runtime\runtime.js:147:19 in PromiseImpl.resolve.then$argument_1
- node_modules\promise\setimmediate\core.js:37:14 in tryCallOne
- node_modules\promise\setimmediate\core.js:123:25 in setImmediate$argument_0
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:146:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:194:17 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:407:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:143:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue

Warning: %s: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to 
display an error message or fallback UI., RootErrorBoundary
- node_modules\react-native\Libraries\YellowBox\YellowBox.js:63:8 in console.error
- node_modules\expo\build\environment\muteWarnings.fx.js:27:24 in error
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:645:36 in warningWithoutStack
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18056:16 in callback      
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:7595:16 in callCallback   
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:7639:19 in commitUpdateEffects
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:7630:22 in commitUpdateQueue
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17116:10 in commitLifeCycles
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:20002:23 in commitLayoutEffects
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:307:15 in invokeGuardedCallbackImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:531:36 in invokeGuardedCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19768:10 in commitRootImpl* [native code]:null in commitRootImpl
- node_modules\react-native\node_modules\scheduler\cjs\scheduler.development.js:643:23 in unstable_runWithPriority  
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19590:4 in commitRoot     
* [native code]:null in commitRoot
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18709:28 in runRootCallback
* [native code]:null in runRootCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5642:32 in runWithPriority$argument_1
- node_modules\react-native\node_modules\scheduler\cjs\scheduler.development.js:643:23 in unstable_runWithPriority
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5638:22 in flushSyncCallbackQueueImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5627:28 in flushSyncCallbackQueue
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18556:30 in scheduleUpdateOnFiber
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:11484:17 in dispatchAction* [native code]:null in dispatchAction
* App.js:51:4 in loadResourcesAndDataAsync
- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
- node_modules\regenerator-runtime\runtime.js:274:30 in invoke
- node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
- node_modules\regenerator-runtime\runtime.js:135:28 in invoke
- node_modules\regenerator-runtime\runtime.js:147:19 in PromiseImpl.resolve.then$argument_1
- node_modules\promise\setimmediate\core.js:37:14 in tryCallOne
- node_modules\promise\setimmediate\core.js:123:25 in setImmediate$argument_0
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:146:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:194:17 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:407:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:143:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
`

**Comment by seven7hell** [comment]
Please share the package.json file.

**Comment by raajnadar** [comment]
@MichaelGorski upgrade to latest version first & then `expo start -c`

**Comment by MichaelGorski** [comment]
`{
	"main": "node_modules/expo/AppEntry.js",
	"scripts": {
		"start": "expo start",
		"android": "expo start --android",
		"ios": "expo start --ios",
		"web": "expo start --web",
		"eject": "expo eject",
		"test": "jest --watchAll"
	},
	"jest": {
		"preset": "jest-expo"
	},
	"dependencies": {
		"@apollo/react-hooks": "^3.1.5",
		"@expo/vector-icons": "~10.0.0",
		"@react-native-community/async-storage": "^1.9.0",
		"@react-native-community/masked-view": "^0.1.9",
		"@react-navigation/bottom-tabs": "^5.2.7",
		"@react-navigation/drawer": "^5.5.0",
		"@react-navigation/material-bottom-tabs": "^5.1.9",
		"@react-navigation/material-top-tabs": "^5.1.9",
		"@react-navigation/native": "^5.1.6",
		"@react-navigation/stack": "^5.2.13",
		"@react-navigation/web": "~1.0.0-alpha.9",
		"apollo-boost": "^0.4.7",
		"apollo-cache-inmemory": "^1.6.5",
		"apollo-client": "^2.6.8",
		"apollo-link": "^1.2.14",
		"apollo-link-rest": "^0.8.0-beta.0",
		"expo": "^37.0.7",
		"expo-asset": "^8.1.4",
		"expo-constants": "^9.0.0",
		"expo-font": "^8.1.1",
		"expo-linear-gradient": "^8.1.0",
		"expo-sqlite": "^8.1.0",
		"expo-web-browser": "^8.2.0",
		"formik": "^2.1.4",
		"gql": "^1.1.2",
		"graphql": "^15.0.0",
		"graphql-anywhere": "^4.2.6",
		"graphql-tag": "^2.10.3",
		"react": "^16.13.1",
		"react-dom": "^16.13.1",
		"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
		"react-native-countdown-component": "^2.7.1",
		"react-native-gesture-handler": "^1.6.1",
		"react-native-modal": "^11.5.6",
		"react-native-paper": "^3.8.0",
		"react-native-progress": "^4.1.2",
		"react-native-reanimated": "^1.8.0",
		"react-native-responsive-screen": "^1.4.1",
		"react-native-safe-area-context": "^0.7.3",
		"react-native-screens": "^2.5.0",
		"react-native-tab-view": "^2.14.0",
		"react-native-web": "^0.12.2",
		"styled-components": "^5.1.0",
		"uuid": "^7.0.3",
		"yup": "^0.28.4"
	},
	"devDependencies": {
		"@babel/core": "^7.9.0",
		"@babel/plugin-proposal-decorators": "^7.8.3",
		"babel-preset-expo": "^8.1.0",
		"jest-expo": "^37.0.0",
		"reactotron-react-native": "^5.0.0"
	},
	"private": true,
	"proxy": "http://localhost:5000"
}
`

**Comment by MichaelGorski** [comment]
@raajnadar I already updated to the newest version, nothing changed.

**Comment by seven7hell** [comment]
` "@react-navigation/native": "^5.1.6",`

Here is the problem. This issue resolved in 5.2.* version.

Please go to the project folder and open any cmd and type below command:

`expo install  @react-navigation/native`

After completion of this, go to the project folder and delete **node_modules** folder. And then again go to cmd and type below command:

`yarn install`

**Comment by MichaelGorski** [comment]
> @MichaelGorski upgrade to latest version first & then `expo start -c`

this worked for me thanks!

**Comment by raajnadar** [comment]
> > @MichaelGorski upgrade to latest version first & then `expo start -c`
> 
> this worked for me thanks!

That is what I said upgrade to latest version.

**Comment by skyequation** [comment]
> @MichaelGorski upgrade to latest version first & then `expo start -c`

It worked! Thanks

**Comment by AAwaisYaseen** [comment]
> @Charis-W I had the same issue, make sure you are using the latest version of `@react-navigation/native`

Was having the same issue , solved it by Updating version of react-navigation/native

**Comment by v8187** [comment]
I am still facing same issue. Using following versions:

"@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/drawer": "^5.8.2",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",

**Comment by raajnadar** [comment]
@v8187 you are still facing the issue because you are using old version. Read the above comments carefully and fix the issue.

**Comment by v8187** [comment]
> @v8187 you are still facing the issue because you are using old version. Read the above comments carefully and fix the issue.

I cleaned npm cache and reinstalled all packages today only. as mentioned in my comment, I am using version 5.5.* which is higher than 5.2.*

**Comment by raajnadar** [comment]
@v8187 clear the metro cache `npx react-native run-android` or `expo start -c`

**Comment by v8187** [comment]
> @v8187 clear the metro cache `npx react-native run-android` or `expo start -c`
> 
> P.S - in my last comment old version = cached version, the term that I used was wrong for cache.

I have done following steps multiple times:

- Removed node_modules folder manually
- npm cache clear
- Reinstalled packages 
- ran `gradlew clean` command in android folder 
- I always start app using `npx react-native run-android`

**Comment by raajnadar** [comment]
Use this cmd `npx react-native run-android --reset-cache`

**Comment by v8187** [comment]
> Use this cmd `npx react-native run-android --reset-cache`

Din't help

**Comment by zeque98** [comment]
Make sure the version of `@react-navigation/stack` and `@react-navigation/bottom-tabs` are the same

example:
```
    "@react-navigation/bottom-tabs": "5.2.1",
    "@react-navigation/native": "5.1.5",
    "@react-navigation/stack": "5.2.10",
```
