### ISSUE TITLE
export type doesn't work

### ISSUE THREAD

**Issue by KJoobin** [react-navigation/react-navigation#8399]
**Current Behavior**

<img width="1198" alt="스크린샷 2020-06-09 오후 3 59 39" src="https://user-images.githubusercontent.com/45376611/84116204-55258900-aa6a-11ea-8d8d-43fa4eba88ef.png">

when i used stack navigation prop type, i has found error in 
```
import {StackNavigationProp} from '@React-navigation/stack'
```

and i see 

<img width="1680" alt="스크린샷 2020-06-09 오후 3 59 44" src="https://user-images.githubusercontent.com/45376611/84116325-8ef68f80-aa6a-11ea-8cbc-a0fc6ae591ec.png">
- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

**Expected Behavior**

when  remove type
```
export { 
    StackNavigationOptions,
    StackNavigationProp,
    StackScreenProps, 
    StackHeaderProps, 
    StackHeaderLeftButtonProps,
    StackHeaderTitleProps, 
    StackCardInterpolatedStyle, 
    StackCardInterpolationProps, 
    StackCardStyleInterpolator, 
    StackHeaderInterpolatedStyle, 
    StackHeaderInterpolationProps, 
    StackHeaderStyleInterpolator, 
} from './types';
```

it was work
what is the problem?
- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.5.0
| @react-navigation/stack        | 5.4.1
| react-native-gesture-handler   | ~1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | ~2.2.0
| react-native                   | in expo
| expo                           | ~37.0.3
| node                           |10.19.0
| npm or yarn                    | 1.16.0

**Comment by raajnadar** [comment]
Upgrade typescript & @babel/core version clear the cache and run the app again the warning will go away.

**Comment by Youn-ha** [comment]
Hi @raajnadar , I thank a lot for your informative reply. I tried running
```
yarn upgrade @babel/core --latest
yarn upgrade typescript --latest
yarn cache clean
```
though, the error remains.
I restarted my IDE and nothing changes.
Do you have any idea?
Thank you.

@react-navigation/stack/lib/typescript/src/index.d.ts
<img width="919" alt="스크린샷 2020-06-24 오후 1 44 41" src="https://user-images.githubusercontent.com/49135241/85501745-ebd47700-b620-11ea-9764-e58dad57adad.png">

RootStackNavigator.tsx
<img width="680" alt="스크린샷 2020-06-24 오후 1 44 49" src="https://user-images.githubusercontent.com/49135241/85501765-f4c54880-b620-11ea-8b14-2c9f91e2f7e6.png">

**Comment by raajnadar** [comment]
Clear the metro cache `npx react-native run-android --reset-cache`

**Comment by Youn-ha** [comment]
> Clear the metro cache `npx react-native run-android --reset-cache`

https://github.com/react-navigation/react-navigation/issues/7981#issuecomment-611377210

Tried this reply that you wrote,
and also tried every other solutions..
  - cleaning cache
  - deleting node_modules and lock file
  - upgrading version of babel-core and babel-runtime
It worked for a while. like... 5 minutes?
I checked @react-navigation/stack/lib/typescript/src/index.d.ts file and saw the error was resolved.
But then my typescript code didn't work. All codes related to type got error.
And about 5 minutes, it started to show same error - "has no exported member StackNavigationProp" - again.
Such a mystery...

**Comment by sorakthunly** [comment]
Can confirm it's happening on a fresh expo project. Why is this closed? @raajnadar

**Comment by raajnadar** [comment]
@sorakthunly I gave the solution to solve this problem `expo start -c` after upgrading @babel/core and typescript to latest.

**Comment by marcusviniciusf** [comment]
I've the same problem. I'd all the instructed steps. But with no results.
I'm using 
```
    "@react-navigation/bottom-tabs": "^5.2.4",
    "@react-navigation/material-top-tabs": "^5.1.7",
    "@react-navigation/native": "^5.1.3",
    "@react-navigation/stack": "^5.7.0",
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "typescript": "^3.8.3"
```
Ps.: I'm not using expo.

**Comment by Charles0818** [comment]
Still experiencing same issue with @react-navigation/stack v5.9.0. Below are my dependencies
![IMG_20200831_095230_729](https://user-images.githubusercontent.com/52771676/91821852-e00fbd00-ec2e-11ea-8536-09911c8c1e6c.jpg)

**Comment by KristenLeach** [comment]
I am still seeing this error as well; I have updated all of my packages, thrown away node modules/pod.lock/pods and reinstalled, cleared metro cache; all the things. I am still seeing this error. The linked issue above also did not solve the problem; as in that one they suggest updating a babel package (which I did) and adding type to the import; still no luck.

**Comment by raajnadar** [comment]
@Charles0818 & @KristenLeach try following this thread https://github.com/react-navigation/react-navigation/issues/7981#issuecomment-611377210 your issue should get fixed.

**Comment by MariaMironets** [comment]
Possible solution:

Check your **VSCode TypeScript** version 

<img width="134" alt="Screenshot 2021-08-24 at 5 41 01 PM" src="https://user-images.githubusercontent.com/20289151/130637204-b9672615-8ff9-4474-b11f-2a87885f7f02.png">

<img width="592" alt="Screenshot 2021-08-24 at 5 40 42 PM" src="https://user-images.githubusercontent.com/20289151/130637138-341a61eb-18ea-423a-8505-009d7b052581.png">
