### ISSUE TITLE
headerRight component gets repositioned and cut off on iOS (intermittent)

### ISSUE THREAD

**Issue by pranavchary** [react-navigation/react-navigation#8657]
**Current Behavior**

- the `headerRight` component sometimes gets moved when reloading the app and ends up getting cut off
![image](https://user-images.githubusercontent.com/32684245/88961354-89e3de80-d26a-11ea-836b-a6608064e67f.png)

**Expected Behavior**
- the header button component should stay in place at all times on iOS devices
![image](https://user-images.githubusercontent.com/32684245/88964904-a2a2c300-d26f-11ea-8694-59b338986796.png)

**How to reproduce**

- This issue occurs randomly and can change from screen to screen on different reloads, so I haven't found a way to consistently reproduce it.
- I did verify that I am up to date on all packages
- Link to the [Snack](https://snack.expo.io/@pchary/db1ab5) (The snack does not run because there are some React hooks used in the code, but the code could be used as a reference to try and reproduce the issue)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | ^5.7.2
| react-native                   | 0.62
| expo                           | 38
| node                           | 10.13.0
| npm or yarn                    | yarn

**Comment by BerkeAras** [comment]
Same issue. Any updates on this?

**Comment by jpaas** [comment]
Having similar issue, but in my case the component isn't repositioned, just cut off at the top.

![Simulator Screen Shot - iPhone 13 - 2022-07-21 at 08 48 44](https://user-images.githubusercontent.com/1231716/180217331-cbee42a9-2a9f-4e6d-ae2e-4ea1f42f6f99.png)

![Simulator Screen Shot - iPhone 13 - 2022-07-21 at 08 48 57](https://user-images.githubusercontent.com/1231716/180217375-688285c0-f5d5-42ae-83bb-be85ed55e9fe.png)

I've seen it when the app regains focus, but I can also reliably reproduce it in a stack navigator.

I have stack navigators nested in tabs. When I navigate to a tab, the `headerRight` is rendered correctly on the root screen in the stack. But when I push another screen onto the stack it gets cut off at the top. If I navigate back to the root, it remains cut off.

From what I can tell using the component inspector, my component is not being resized. It's being rendered inside a `react-native-screens` component called `ScreenStackHeaderRightView`. When extra screens get pushed on the stack, that view starts clipping its contents.

I've tried using `onLayout` to get the available height, but it never seems to give the right number. It always yields 52 which is too large and my button ends up clipped. So I have no idea how to size my button to fit.

**Comment by jarrodparkes** [comment]
I am having a similar problem:

![same-problem-header-right](https://user-images.githubusercontent.com/1331063/187995106-448ae240-2df6-4879-b593-4ce471183716.png)

Anyone find a solution for this?

**Comment by wangqiannan** [comment]
Maybe you should update the headerRight in useLayoutEffect hook instead of useEffect.

**Comment by koenBconnect** [comment]
Hello, this problem is occurring with my application as well. This problem does not seem to occur on my Iphone 11 pro max, but on the 12 and higher it does. Any suggestions to fix this?
![image](https://user-images.githubusercontent.com/98891472/215132561-05e29d73-7d84-44db-90e8-01c8a545791e.png)

**Comment by heyalexchoi** [comment]
having this issue on iOS native stack header
```
    "react-native": "^0.70.13", 
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.9.13",
    "@react-navigation/stack": "^6.2.2",
```

**Comment by DuncanLewis** [comment]
I encountered the same issue, it was intermittent on iOS 16 but, on devices running iOS 17 it was happening 100% of the time on release builds - note that it didn't occur at all on debug builds to simulator or real devices (via USB). 

Only workaround was to implement the header manually and hide the react navigation header with `headerShown: false` - far from ideal and this really needs addressing.

**Comment by tobyshi** [comment]
I went through a number of trials and errors. 
In my example, I'm adding a TouchableOpacity with a nested "more" icon and set the position 'absolute'
This fixed the positioning but the onPress Event is not being triggered. Tried a few things without success. 
Maybe someone has a solution for that?

`<TouchableOpacity
              style={{ backgroundColor: "green", position: "absolute" }}
              onPress={() => router.push("/settings")}
            >
              <Feather
                name="more-horizontal"
                size={32}
                color={globalColors.textDefault}
              />
            </TouchableOpacity>`

**Comment by tristan0508** [comment]
Found a quick and easy solution for the time being, seems like there is a slight delay on the correct properties being loaded, as when I navigate away and back it fixes it. I added this delay in, and it comes in perfect every time so far. 


```const Layout = () => {
  const [delay, setDelay] = useState(false);

  useEffect(() => {
    setTimeout(() => setDelay(true), 100);
  }, []);
  return (
    <Stack>
      <Stack.Screen
        name="index"
        options={{
          headerTransparent: true,
          contentStyle: { backgroundColor: "transparent" },
          title: "Home",
          headerTitle: HeaderTitle,
          headerRight: () => {
            return delay ? <RightHeader /> : null;
          },
        }}
      />
    </Stack>
  );
};

export default Layout;```

**Comment by JcbPrn** [comment]
This issue is also occurring for me when using native stack. Icons are rendering normally with normal stacks.

**Comment by brimby** [comment]
> Found a quick and easy solution for the time being. I added this delay in, as it seems like a loading issue.

I'm glad you found a workaround and i kind of figured it was a timing thing, but delays are like my last favorite hacks. I hope someone can figure this one out eventually. I'll just reiterate that switching to the regular stack from the native stack works. But yeah of course I'd rather be using the native one.

**Comment by daamsie** [comment]
Please re-open this issue. It is still a problem and should be addressed. Very annoying.

**Comment by Misha327** [comment]
Having the same issue with headerRight, also headerLeft is not pressable while this bug is occuring.

**Comment by fredrikburmester** [comment]
I have the same issue.

**Comment by RamanSB** [comment]
This issue should not be closed, I am still experiencing this and must use a delay...

**Comment by bilal1031** [comment]
> This issue should not be closed, I am still experiencing this and must use a delay...

Is there any open request for this issue?

**Comment by antoniotex** [comment]
I have the same issue, 2024, four years, none solution

**Comment by michaelThomasCollins** [comment]
Not sure if this helps anyone but I resolved the issue by removing my components from a View and adding them to a blank tag like so
<>
<Button/><Button/>
</>

**Comment by igorm-cr** [comment]
Why is this closed...

**Comment by ftaibi** [comment]
I found a solution. Instead of setting headerShown: false in the main Navigator, instead just disable the header on each screen:

    <MainStack.Screen
        options={{
          headerShown: false,
        }}

**Comment by ftaibi** [comment]
SOMEONE PLEASE FIX THIS ITS BEEN 4 YEARS!!!

**Comment by brimby** [comment]
USE THE REGULAR STACK, NOT THE NATIVE STACK! YOU WON'T NOTICE ANY DIFFERENCE EXCEPT THAT IT WILL WORK!!!

**Comment by alehano** [comment]
I figured out that the issue is related to the dynamic parameters used in the header.

In my case, I have:

<Stack
        screenOptions={{
          headerStyle: {
            backgroundColor: theme.headerBackground,
          },
          headerTitleStyle: {
            color: theme.text,
          },
          contentStyle: { backgroundColor: theme.background },
        }}
      >

If I change the colors to fixed values, it works fine.
theme is using ModX state values, and maybe it's related to the order of loading, etc. Sometimes, when loading the app, headerRight is just inserted after the header boundary.

**Comment by timgcarlson** [comment]
This is definitely still an issue. I'm seeing this behavior when using expo-router but only when an app has been deployed to TestFlight. I cannot reproduce this in a local build. Can this be reopened or is there another issue that is tracking this bug?

**Comment by mykola-parfenov-axon** [comment]
Guys this is still an issue and is reproducing only in a real build, not local development one, so it is even more disturbing

**Comment by lsmarcos** [comment]
Same issue. Any updates on this?

**Comment by huedaya** [comment]
Can confirm adding delay works.

```tsx
  useEffect(() => {
    setTimeout(() => {
      navigation.setOptions({
        headerRight: () => (
          <TouchableOpacity
            onPress={() => {
             //
            }}
          >
            <Text>
              Mark All
            </Text>
          </TouchableOpacity>
        ),
      });
    }, 300);
  }, [navigation]);
```

**Comment by fredrikburmester** [comment]
I'm still having this issue on Expo 53 and react-navigation 0.9.0.

**Comment by rvasseur31** [comment]
> Can confirm adding delay works.
> 
>   useEffect(() => {
>     setTimeout(() => {
>       navigation.setOptions({
>         headerRight: () => (
>           <TouchableOpacity
>             onPress={() => {
>              //
>             }}
>           >
>             <Text>
>               Mark All
>             </Text>
>           </TouchableOpacity>
>         ),
>       });
>     }, 300);
>   }, [navigation]);

In my case, I fixed it with :
```
  useLayoutEffect(() => {
    navigation.setOptions({
      headerRight: undefined,
    })
    setTimeout(() => {
      navigation.setOptions({
        headerRight: HeaderRightMenu,
      })
    }, 0)
  }, [HeaderRightMenu, navigation])
```

**Comment by Michota** [comment]
Reopen the issue!

**Comment by Michota** [comment]
Updating the `react-native-screens` to version `4.11.0-nightly-20250515-b673a0cff` worked for me.

**Comment by ShivamQmr** [comment]
It is still an issue with latest versions as of July 9, 2025. Using `import { createStackNavigator } from '@react-navigation/stack'`, however solves the issue. But for native stack it's still an issue.

**Comment by ktphuc1994** [comment]
It is still an issue as of August 2025. In my case, the headerRight sometime shows up, but most of the time it is not rendered. So I have to use the useEffect workaround.
```js
const [isLoading, setIsLoading] = useState(true);

useEffect(() => {
    setTimeout(() => {
      setIsLoading(false);
    }, 100);
}, []);
```

```json
"@react-navigation/native": "^7.1.14",
"@react-navigation/native-stack": "^7.3.21",
"expo": "~53.0.17",
"expo-image-picker": "~16.1.4",
"expo-status-bar": "~2.2.3",
"react": "19.0.0",
"react-native": "0.79.5",
"react-native-safe-area-context": "5.4.0",
"react-native-screens": "~4.11.1"
```

**Comment by MobileMon** [comment]
Still an issue. This needs reopened

**Comment by SamJonesUK** [comment]
Still an issue sadly
