### ISSUE TITLE
Bottom tabs are too low on iPhone 12 Series phones

### ISSUE THREAD

**Issue by marcinkornek** [react-navigation/react-navigation#8972]
**Current Behavior**

Bottom Tabs are below iPhone Swipe Indicator on iPhone 12 Series (tested on iPhone 12, 12 Pro, 12 Pro Max simulators in Xcode 12.1)

I created new simple app to reproduce problem:
```import React from 'react';
import { Text } from 'react-native';
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import { createBottomTabNavigator } from 'react-navigation-tabs';

const HomeScreen = () => (
  <Text>Home Screen</Text>
)

const ProfileScreen = () => (
  <Text>Profile Screen</Text>
)

const Tabs = createBottomTabNavigator(
  {
    HomeScreen: {
      screen: HomeScreen,
      path: 'market',
    },
    ProfileScreen: {
      screen: ProfileScreen,
      path: 'profile',
    },
  }
);

const AppNavigator = createStackNavigator({
  Tabs: {
    screen: Tabs,
  },
});

export default createAppContainer(AppNavigator);
```
Here how code above looks on iPhone 12, iPhone 11 and iPhone 8 simulators (Xcode 12.1)
![image](https://user-images.githubusercontent.com/7931279/96848865-393ce580-1455-11eb-83f0-024c1b8ba3e4.png)

I was checking react-native-tabs source code and looks like `safeAreaInset` `bottom` param is not working. When I change it to 'never', it also breaks on iPhone 11 https://github.com/react-navigation/tabs/blob/master/src/views/BottomTabBar.tsx#L103
Here's the screenshot with `safeAreaInset` with `bottom: 'never'`
```
  safeAreaInset: {
    bottom: 'never',
    top: 'never'
  }
```
![image](https://user-images.githubusercontent.com/7931279/96851294-2841a380-1458-11eb-9b58-c475818d1476.png)

**Expected Behavior**

Bottom Tabs should look the same on iPhone 12 as they look on iPhone 11.

**How to reproduce**

Use tabs from `react-native-tabs` on iPhone 12 Series phone

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 |
| react-navigation   |    ^4.4.2        |
| react-navigation-stack  |  ^2.8.4     |
| react-navigation-tabs   |   ^2.9.2    |
| react-native-reanimated  |^1.13.1      |
| react-native-gesture-handler | ^1.8.0 |
| react-native-safe-area-context | ^3.1.8 |
| react-native-screens |   ^2.11.0       |
| react-native      |      0.63.3       |
| node      |    v13.8.0                 |
| yarn     |  1.22.0             |

**Comment by marcinkornek** [comment]
I found a way to fix it. 
What I did:
* I wrapped whole app in `SafeAreaProvider`:
```
import { SafeAreaProvider, initialWindowMetrics } from 'react-native-safe-area-context'

[...]

<SafeAreaProvider initialMetrics={initialWindowMetrics}>
  <AppContainer />
</SafeAreaProvider>
```
* Added dependency `react-native-safe-area-view: "^2.0.0"` (`react-navigation-tabs 2.9.1` uses `react-native-safe-area-view "^0.14.9"`)
* forced to use this dependency - added this code to package.json below devDependencies (but can be anywhere on main level):
```
  "resolutions": {
    "react-native-safe-area-view": "^2.0.0"
  },
```

Here how the code looks like:
```
import React from 'react';
import { Text } from 'react-native';
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import { createBottomTabNavigator } from 'react-navigation-tabs';
import { SafeAreaProvider,  initialWindowMetrics } from 'react-native-safe-area-context' <--- added this

const HomeScreen = () => (
  <Text>Home Screen</Text>
)

const ProfileScreen = () => (
  <Text>Profile Screen</Text>
)

const Tabs = createBottomTabNavigator(
  {
    HomeScreen: {
      screen: HomeScreen,
      path: 'market',
    },
    ProfileScreen: {
      screen: ProfileScreen,
      path: 'profile',
    },
  }
);

const AppNavigator = createStackNavigator({
  Tabs: {
    screen: Tabs,
  },
});

const AppContainer = createAppContainer(AppNavigator)

const App = () => (
  <SafeAreaProvider initialMetrics={initialWindowMetrics}>   <---- wrapped whole app
    <AppContainer />
  </SafeAreaProvider>
)

export default App
```

and here how it works:
![image](https://user-images.githubusercontent.com/7931279/96874356-51712c80-1476-11eb-9a69-ae5193b592c5.png)

**Comment by wildseansy** [comment]
Thanks for the rec @marcinkornek - that worked for me.  I didn't have to use a `SafeAreaProvider` either.  I'm guessing the version of react-navigation I'm using accounts for this.

**Comment by Vednus** [comment]
Strange, I have the top being compressed and the bottom looking fine on iPhone 12. Using react-navigation v4. Similar to this: https://github.com/react-navigation/react-navigation/issues/2589

**Comment by gdoudeng** [comment]
+1

**Comment by alexandersandberg** [comment]
Upgrading to the latest versions of `react-navigation` (I'm using v4), `react-navigation-tabs`, and `react-native-safe-area-context` did it for me.

**Comment by ericwrobinson** [comment]
@marcinkornek  I saw your issue [here](https://github.com/react-navigation/react-native-safe-area-view/issues/136) too, how did you fix the safe-area-view for the heading?

**Comment by satya164** [comment]
Closing since it's fixed in latest version of react-navigation-tabs.

**Comment by aaronleo28** [comment]
I had the same issue with @react-navigation/material-bottom-tabs, @marcinkornek solution partially worked, i had to run the following commands in addition to his detailed steps

`yarn add react-native-safe-area-context`

and add react-native-paper to the package.json resolutions

```
 "resolutions": {
    "react-native-paper": "^4.3.0",
    "react-native-safe-area-view": "^2.0.0"
  },
```

**Comment by kyaroru** [comment]
To those who face the same issue as me after updating to latest version...

After following the steps to update to latest version of `react-navigation` fixed the bottom tab issue + header issue
    "react-navigation": "4.4.3",
    "react-navigation-stack": "^2.10.1",
    "react-navigation-tabs": "2.10.1",

But I got another issue only happening on Android 10 due to this section [for animation](https://github.com/react-navigation/react-navigation/commit/6bdc1e9e5f6ca05e0494f6b9a1f7b9b60764628a#r44196297) . 

When you are using mode: 'modal' in your StackNavigator & your modal are just partial screen (not full screen). The background will be blank instead of see through view.

![image](https://user-images.githubusercontent.com/1030024/99188191-99ddea80-2795-11eb-966d-3e4ad94e52f4.png)

 To fix it temporary: I revert back animation to RevealFromBottomAndroid instead of ScaleFromCenterAndroid (which is for Android 10 by default).

![image](https://user-images.githubusercontent.com/1030024/99188217-bf6af400-2795-11eb-94af-67536994acbe.png)

**Comment by Juliocbr** [comment]
same issue with: 
"@react-navigation/bottom-tabs": "^5.11.0",
"@react-navigation/material-top-tabs": "^5.3.9",
"@react-navigation/native": "^5.8.7",
"@react-navigation/stack": "^5.12.5",

**Comment by alexandersandberg** [comment]
I just noticed that I'm still experiencing this issue on an iPad Air (4th gen, 2020) running iOS 14.4.

Updating to the latest versions (as recommended in [my previous comment](https://github.com/react-navigation/react-navigation/issues/8972#issuecomment-717248649)) only fixes it for iPhone.

**Comment by tharindu1989** [comment]
Not sure this will help to anyone, But I had a similar issue, Which I use a SafeAreaView for ScrollView and bottom margin was not there. But same Container when I apply to TabBar it was working as expected. Issue was I had to set the scrollView height as `{ height:"100%" }`.

**Comment by Zilleabbas10** [comment]
@kyaroru @marcinkornek I am using typescript 3.6.3 but getting type errors in react-navigation-stack after updating libraries as you suggested. Can you let me know what typescript version you are using. Thanks

**Comment by alexandersandberg** [comment]
@punndcoder28 Make sure you fix any breaking changes between your previous version and the one you upgraded to.

**Comment by punndcoder28** [comment]
Thanks @alexandersandberg it work!

**Comment by AxeneDeveloper-19** [comment]
Hello,

Any fixes for react-native version 0.59.10?

As I had tried some of solution given above but it will required higher version fo react-native.

**Comment by alessiocancian** [comment]
Had the same problem, fixed by updating `react-native-paper` as found here https://github.com/react-navigation/react-navigation/issues/9110#issuecomment-767608726

**Comment by HarveyNgo** [comment]
> Hello,
> 
> Any fixes for react-native version 0.59.10?
> 
> "react-navigation": "^2.18.3",
> "react": "^16.8.6",
> "react-native": "^0.59.10",
> 
> As I had tried some of solution given above but it will required higher version fo react-native.
> 
> So I am not able to use - "react-native-safe-area-view": "^2.0.0" this.


Hi @AxeneDeveloper-19 , 
I using "react-navigation":"2.2.0", same with u, which unable to use react-native-safe-area-view
so here I my work around:
detect if device's height is iphone 12, and set marginBottom for it 
hope it help

--------------------------------------------
const IPHONE12_H = 844;
const IPHONE12_Max = 926;
const IPHONE12_Mini = 780;
const { height: D_HEIGHT, width: D_WIDTH } = Dimensions.get('window');

tabBarOptions: {
     style: {
            marginBottom:
                        Platform.OS === 'ios' &&
                        (D_HEIGHT === IPHONE12_H ||
                          D_HEIGHT === IPHONE12_Max ||
                          D_HEIGHT === IPHONE12_Mini)
                          ? 20 : 0
     }
}

**Comment by phonezawphyo** [comment]
For those who are still on react-navigation-tabs@^2.11.2, the issue exists for iPhone 13+ Pro (Max).
It is due to the library being dependent on `react-native-iphone-x-helper` which is no longer maintained.

My solution is to disable auto bottom insets and use SaveAreaView manually as belows.

```js
const TabNavigator = createBottomTabNavigator({
  // Screens
}, {
  tabBarOptions: {
      safeAreaInset: {
        bottom: 'never',
      }
  }
}
```

```js
  
  render() {
    const { navigation } = this.props
    const viewRef = React.createRef()

    return (
      <SafeAreaView>
        <TabNavigator ref={viewRef} navigation={navigation}/>
      </SafeAreaView>
    )
  }
```

I hope it helps!

**Comment by Aycom366** [comment]
Incase you're using expo router and you'd like to follow @phonezawphyo did. 
```
<SafeAreaView style={tw`flex-1`}>
      <Tabs
        safeAreaInsets={{ bottom: 0 }}
        screenOptions={{
          headerShown: false,
          tabBarShowLabel: false,
          tabBarStyle: {
            borderTopRightRadius: 20,
            borderTopLeftRadius: 20,
            height: 76,
            backgroundColor: isDark ? "#111111" : "white",
          },
        }}
      >
        <Tabs.Screen
          name="home"
          options={{
            tabBarIcon: () => <TabIcon isDark={isDark} name="Home" icon={isDark ? icons.homeWhite : icons.homeBlack} />,
          }}
        />
 </Tabs>
    </SafeAreaView>
```
