### ISSUE TITLE
'Back' icon button is not showing for iOS14.0 simulator

### ISSUE THREAD

**Issue by jko12130** [react-navigation/react-navigation#9075]
**Current Behavior**

-For the stack navigator, the default 'back' icon button is not showing for the iOS simulator. 
-The icon is not showing, but when I click on where the icon is supposed to be, it actually works.
-This one used to show without any problem. Is this a known currently ongoing issue?

**Expected Behavior**

- Show 'back' icons for the stack navigator

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS 14.2
| @react-navigation/native      | "^5.8.9"
| @react-navigation/bottom-tabs | "^5.8.9"
| @react-navigation/stack | "^5.9.2"
| react-native-screens          | "^2.11.0"
| react-native                  | "^0.62.2"
| expo                          | "^38.0.0"

**Comment by jko12130** [comment]
Hi, the issue persists after upgrading the packages to the latest versions.
Headers and titles appear without any problem. Back button titles also appears. Just the back button icons are missing across all the screens!

**Comment by jko12130** [comment]
Hello, this issue is still happening. Could someone look into this?
FYI, on Android, 'back' icons are all properly displayed. Only on iOS (and potentially 14.2) this issue is happening.

**Comment by Naturalclar** [comment]
@jko12130 I believe the issue has to do with react-native itself with iOS14 rather than react-navigation.
For react-native 0.62.2, you'd need to patch react-native in order to display image on iOS14. https://github.com/facebook/react-native/issues/29279
The problem is solved with newer versions of react-native

**Comment by jko12130** [comment]
> @jko12130 I believe the issue has to do with react-native itself with iOS14 rather than react-navigation.
> For react-native 0.62.2, you'd need to patch react-native in order to display image on iOS14. [facebook/react-native#29279](https://github.com/facebook/react-native/issues/29279)
> The problem is solved with newer versions of react-native

Works perfectly. Thanks!!!

**Comment by AugustoAleGon** [comment]
I still have this problem. In my case I have the same problem just with Production environment after archived.

**Comment by iquabius** [comment]
I had this issue on Android and setting up `server.enhanceMiddleware` in Metro configuration solved it for me. The function implementation can [be found here](https://github.com/expo/expo/issues/7545#issuecomment-712737616). For React Navigation only the second half of the function is necessary.
