### ISSUE TITLE
react-native-gesture-handler module was not found. Make sure you're running your app on the native platform and your code is linked properly (cd ios && pod install && cd ..)

### ISSUE THREAD

**Issue by MaxCode-fan** [react-navigation/react-navigation#9385]
Hello, what I want to know is why this problem appears after I operate according to the document. I don't know how to solve it.
![image](https://user-images.githubusercontent.com/57091336/110057518-b41af300-7d9b-11eb-9d5c-c8f98c1f34f6.png)

![image](https://user-images.githubusercontent.com/57091336/110057561-c39a3c00-7d9b-11eb-99d1-c0b1c8fee4ef.png)
My running platform is Win10 and Android mobile phone
![image](https://user-images.githubusercontent.com/57091336/110057677-f8a68e80-7d9b-11eb-80a2-7f5c7e216998.png)
Now I can't click on my screen anymore and it doesn't do anything

**Comment by raajnadar** [comment]
Did you follow the whole setup? https://reactnavigation.org/docs/getting-started#installing-dependencies-into-a-bare-react-native-project

Especially did you add this piece of code on your root file.

`import 'react-native-gesture-handler';`

**Comment by woowalker** [comment]
same problems, any solutions ?
![image](https://user-images.githubusercontent.com/7894779/124738639-b65cac00-df4b-11eb-8b67-e16b8d13656a.png)

**Comment by khdealwis** [comment]
> Hello, what I want to know is why this problem appears after I operate according to the document. I don't know how to solve it. ![image](https://user-images.githubusercontent.com/57091336/110057518-b41af300-7d9b-11eb-9d5c-c8f98c1f34f6.png)
> 
> ![image](https://user-images.githubusercontent.com/57091336/110057561-c39a3c00-7d9b-11eb-99d1-c0b1c8fee4ef.png) My running platform is Win10 and Android mobile phone ![image](https://user-images.githubusercontent.com/57091336/110057677-f8a68e80-7d9b-11eb-80a2-7f5c7e216998.png) Now I can't click on my screen anymore and it doesn't do anything

Hey, could you find a solution for this?

**Comment by khdealwis** [comment]
@MaxCode-fan did you find any solution for this?

**Comment by suvinrj** [comment]
Same for me. Did you find any solution?

**Comment by privatepej** [comment]
any solution guys?

**Comment by praveenreddy9** [comment]
Hi,
 "react": "18.1.0",
 "react-native": "^0.70.3",
 "react-navigation": "^4.4.4",
  "react-navigation-stack": "^2.10.4",
  "react-native-gesture-handler": "^2.7.1",
  
  Am using all the above versions still facing the below issue,Because of gesture issue am unable to use Navigation.
  Please help me in resolving the issue or suggest me an alternate solution.
  
   **ERROR  [react-native-gesture-handler] react-native-gesture-handler module was not found. Make sure you're running your app on the native platform and your code is linked properly (cd ios && pod install && cd ..).

For installation instructions, please refer to https://docs.swmansion.com/react-native-gesture-handler/docs/#installation**


Thanks

**Comment by TacticCoder** [comment]
Same here

**Comment by Jim97M** [comment]
Getting this error too, Did you find any solution?

**Comment by phongbksneep** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/48904562/211525782-4a37b8e1-4d7c-41db-b7d1-331910cfd652.png">
Same for me

**Comment by UchihaSV** [comment]
Same here, i installed by instructions and it's work for expo, but doesn't work for EJECT'ed Expo project, clean cache reinstall do not help, any advice?

**Comment by phongbksneep** [comment]
Does anyone have the workaround ? please

**Comment by phongbksneep** [comment]
I change getPackages in MainApplication like this: 
`        @Override
        protected List<ReactPackage> getPackages() {
          List<ReactPackage> packages = new PackageList(this).getPackages();
          return packages;
        }
`

**Comment by Juman8** [comment]
Hi. make sure you are using match the config in MainApplication.java
I discovered that some projects after initialization will have a different format than the desired config that the bridge wants
Ex:
`return Arrays.<ReactPackage>asList(
                new ....
            );`
but the config have to be:
`@Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          return packages;
        }`
Because your app will not load all the other modules instead of adding it will return a new list with the elements in the returned array.
Hope it helps you.

**Comment by ashwindatye** [comment]
@Juman8 @phongbksneep  Did u solve your problem? My config is like yours. I am still getting same error.
[react-native-gesture-handler] react-native-gesture-handler module was not found. Make sure you're running your app on the native platform and your code is linked properly (cd ios && pod install && cd ..).

For installation instructions, please refer to https://docs.swmansion.com/react-native-gesture-handler/docs/#installation
 ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument., js engine: hermes

I have migrated from 0.63 to 0.70 and also from Intel Mac to M1

~ashwin

**Comment by Juman8** [comment]
> @Juman8 @phongbksneep Did u solve your problem? My config is like yours. I am still getting same error. [react-native-gesture-handler] react-native-gesture-handler module was not found. Make sure you're running your app on the native platform and your code is linked properly (cd ios && pod install && cd ..).
> 
> For installation instructions, please refer to https://docs.swmansion.com/react-native-gesture-handler/docs/#installation ERROR Invariant Violation: `new NativeEventEmitter()` requires a non-null argument., js engine: hermes
> 
> I have migrated from 0.63 to 0.70 and also from Intel Mac to M1
> 
> ~ashwin

hi @ashwindatye 
Is your metro path running and connecting?
As I can see, your code seems to be dead at the JS and get data from bridge layers, right?

**Comment by Kamlesh-62** [comment]
react-native-gesture-handler module was not found. Make sure you're running your app on the native platform and your code is linked properly (cd ios && pod install && cd ..).

For installation instructions, please refer to https://docs.swmansion.com/react-native-gesture-handler/docs/#installation
[Fri Feb 17 2023 11:13:51.135]  ERROR    Invariant Violation: Native module cannot be null.
[Fri Feb 17 2023 11:13:51.135]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

Hello, I am struggling with this error for the last 2 days. I have tried many solutions and suggestions from GitHub and StackOverflow, however, I did not get a solution. 

"react": "16.9.0",
"react-native": "^0.63.3",
"@react-navigation/native": "^5.9.4",
"react-native-gesture-handler": "^1.10.3",
"react-native-reanimated": "^1.13.3",
"react-native-screens": "^2.18.1",  
"@react-navigation/stack": "^5.14.4",
"@react-navigation/drawer": "^5.12.5",

Even I uninstall react-native-gesture-handler from the package from the project still not working.  I used this command npm uninstall  @react-native-gesture-handler --save. 

Some solution says link project, but RN version is higher than 0.60 so I need to do that right!

I'll appreciate your solution.

**Comment by DavidGracias** [comment]
I am getting the same exact issues as above -- please someone who knows how to solve this contact me!

**Comment by sgrund14** [comment]
think I tried everything on here and I'm still getting this same error... in addition to this:

```
ERROR Invariant Violation: new NativeEventEmitter() requires a non-null argument., js engine: hermes
```

I'm using expo in a Yarn workspace... has anyone solved this? Seems similar to what you were getting @ashwindatye

**Comment by JS-GitRepo** [comment]
@sgrund14 

I'm using EAS Development Builds, but building the application resolved the "module not found" issue for me. For testing on android, this was "eas build --profile development --platform android" for me. In a non-eas environment, it may be something like expo prebuild or some other experimentation with building your project might help.

Using React Navigation, wrapping my component prop in gestureHandlerRootHOC() solved my other issues. Screen components in the NavigationContainer looks something like this:

`					<Stack.Screen
						name="Home"
						component={gestureHandlerRootHOC(Home)}
						options={{ headerShown: false }}
					/>`

**Comment by crimson-med** [comment]
Same issue here:

```json
{
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/checkbox": "^0.5.15",
    "@react-native-community/masked-view": "0.1.11",
    "@react-navigation/bottom-tabs": "6.5.7",
    "@react-navigation/native": "~6.1.6",
    "@react-navigation/stack": "~6.3.16",
    "axios": "^1.4.0",
    "expo": "~48.0.16",
    "expo-asset": "~8.9.1",
    "expo-constants": "~14.2.1",
    "expo-font": "~11.1.1",
    "expo-linking": "~4.0.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-web-browser": "~12.1.1",
    "overmind": "^28.0.2",
    "overmind-react": "^29.0.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.7",
    "react-native-appearance": "~0.3.3",
    "react-native-dialog": "^9.3.0",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-web": "~0.18.10",
    "socket.io-client": "^4.6.1"
  },
  "devDependencies": {
    "@babel/core": "^7.21.8",
    "@types/node": "^18.16.3",
    "@types/react": "~18.2.4",
    "@types/react-native": "~0.71.6",
    "jest-expo": "~48.0.2",
    "typescript": "^5.0.4"
  },
}
```


Error: 

```
Android Bundling failed 2926ms
Unable to resolve module react-native-gesture-handler from /react-native-overmind-boilerplate/App.tsx: react-native-gesture-handler could not be found within the project or in these directories:
  node_modules
  ../node_modules
  ../../node_modules
```

I have tried the following:

- Clear cache and restart
- Delete the node modules and re-install
- Delete react-native-gesture-handler and reinstall.

Nothing seems to get rid of this issue.

**Comment by rp121** [comment]
> @sgrund14
> 
> I'm using EAS Development Builds, but building the application resolved the "module not found" issue for me. For testing on android, the command was "eas build --profile development --platform android" ; I assume the ios equivalent may help if youre testing there. In a non-eas environment, it may be something like expo prebuild or some other experimentation with building your project might help.
> 
> Using React Navigation, wrapping my component prop in gestureHandlerRootHOC() solved my other issues. Screen components in the NavigationContainer looks something like this:
> 
> `<Stack.Screen name="Home" component={gestureHandlerRootHOC(Home)} options={{ headerShown: false }} />`

This is what solved it for me, at least on an IOS device (eas build + wrapping gestureHandlerRootHOC function around my screen components).

**Comment by HeyItsJs** [comment]
Hey @crimson-med, I am getting exact same error as you. Did you find any solution for it?

**Comment by RostCode78** [comment]
Yo aplique la vieja confiable, borrar node_modules y ejecutar npm install.
----------------------------------------------------------------------------------
I applied "Old Reliable", delete node_modules and run npm install

**Comment by itheakmal** [comment]
i got issue of some folder not deleting in the build, and build failded, so delted those folder manually then rebuild all fixed

**Comment by danandres281** [comment]
> import 'react-native-gesture-handler';
 i have the same issue, how i fixed, i try deleting the pods and podfile then re installing again but not works, any solution ?

**Comment by rustyonrampage** [comment]
I had this issue with the latest packages. 
ERROR [react-native-gesture-handler] react-native-gesture-handler module was not found.

So I looked in to it and found out for newer versions we need to wrap root view with GestureHandlerRootView.
https://docs.swmansion.com/react-native-gesture-handler/docs/1.10.3/
But even that didn't fix the issue and now I was having another error as well.  "GestureHandlerRootView" was not found in the UIManager.

So I though maybe I should try with fresh node_modules. 
1) First I deleted node_modules folder
2) Deleted package.lock/yarn.lock
3) Cleared yarn cache.
4) Installed the packages again using yarn command
5) When I ran "yarn android". Everything was fine.

Maybe following it'll help you guys.

**Comment by Avetyandav** [comment]
Hey everyone! 
Have the same issue with expo app,  in Expo GO everything works amazing, after 
```
eas build --profile development --platform iOS

```
Start having that gesture-handler problem. 
Even after building empty(new) Expo project and trying to make dev build, have that problem, a soon as I add some navigation to the app.

**Comment by alemachado24** [comment]
Agree! Works perfectly after re building the project 

npx eas-cli build --profile development

npx run start

**Comment by gibo77** [comment]
I have the same issue after installing the react-native-splash-screen and did some changes on the Android files.
I did Rebuild Project in Android Studio and Re-install Gesture-handler, with no luck.

**Comment by AngCosmin** [comment]
I managed to solve the issue by following these [installation steps](https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation)

```
npm install --save react-native-gesture-handler
```

```js
import { GestureHandlerRootView } from 'react-native-gesture-handler';

export default function App() {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      {/* content */}
    </GestureHandlerRootView>
  );
}
```

**Comment by WarutereD** [comment]
> @sgrund14
> 
> I'm using EAS Development Builds, but building the application resolved the "module not found" issue for me. For testing on android, the command was "eas build --profile development --platform android" ; I assume the ios equivalent may help if youre testing there. In a non-eas environment, it may be something like expo prebuild or some other experimentation with building your project might help.
> 
> Using React Navigation, wrapping my component prop in gestureHandlerRootHOC() solved my other issues. Screen components in the NavigationContainer looks something like this:
> 
> `<Stack.Screen name="Home" component={gestureHandlerRootHOC(Home)} options={{ headerShown: false }} />`


This solved the issue for me, for expo 49 and using a eas development build

**Comment by zuxcode** [comment]
I Managed to resolve the problem by rebuilding my project

**Comment by CyxouD** [comment]
As @zuxcode noted In my case for Expo project, I had to write `npx expo prebuild` first to reflect native code changes and only after that `expo run:android`
