### ISSUE TITLE
Android: Material Bottom Tab Nav + Nested Stack Nav causing flicker

### ISSUE THREAD

**Issue by quicksnap** [react-navigation/react-navigation#9560]
**Current Behavior**

Flickering when switching tabs

**Expected Behavior**

No flicker! :)

**How to reproduce**

I've set up a simple example here: 
- https://expo.io/@quicksnap/projects/material-bottom-flicker-repro
- https://github.com/quicksnap/material-bottom-flicker-repro

This is the boilerplate Expo init project, but with react-paper and material bottom tab swapped out. Switching to the second tab will cause a flicker on my phone (Android 11, Pixel 3)

This issue may be related: https://github.com/react-navigation/react-navigation/issues/9256

**Comment by quicksnap** [comment]
Verified issue exists on latest versions. Republishing examples.

**Comment by quicksnap** [comment]
Posted https://github.com/callstack/react-native-paper/issues/2726

**Comment by raajnadar** [comment]
It seems you are missing some steps https://reactnavigation.org/docs/getting-started please read this and update me.

**Comment by quicksnap** [comment]
Hey! Thanks for the reply. Looks like my example was missing `import 'react-native-gesture-handler';`. I tried it out and am still seeing a flicker. I pushed an update to the example repo.

**Comment by raajnadar** [comment]
Can you please try this and update me?

https://github.com/react-navigation/react-navigation/issues/9557#issuecomment-883493628

**Comment by quicksnap** [comment]
I just pushed up new code with `headerShown: false`--no luck.

I also tried specifying height, but there is still flicker.

**Comment by gloredo** [comment]
Same problem here, using last version of all:

```
expo@42.0.3
@react-navigation/native@6.0.2
@react-navigation/stack@6.0.6
@react-navigation/native-stack@6.0.5
@react-navigation/drawer@6.1.3
@react-navigation/material-bottom-tabs@6.0.4
react-native-screens@3.5.0
```

In my case, BottomTabsNavigator is child of the DrawerNavigator.

The result is the same with `stack` and `native-stack`. With `headerMode: 'float'` the header stops flicking, but the header animation when back is slow. 

On iOS, where `headerMode: 'float'` is the default, the header issue is resolved, but the back animation is still broken.

**Comment by raajnadar** [comment]
@gloredo you are using custom header you should try this https://reactnavigation.org/docs/stack-navigator#specify-a-height-in-headerstyle, mostly it will solve your problem.

**Comment by gloredo** [comment]
@raajnadar as mentioned by @quicksnap set header height don't solve the problem.

**Comment by gloredo** [comment]
Update on Expo SDK 43 (RN 64) and React Navigation packages in latest version.
 
Android: Apparently everything is working fine.
iOS: Header "jump" on first interaction with each bottom bar button, back animation looks good.

Tested with `@react-navigation/stack`. I quickly tried it with `@react-navigation/native-stack` but the screen content disappear.

**Comment by ansmlc** [comment]
> Update on Expo SDK 43 (RN 64) and React Navigation packages in latest version.
> 
> Android: Apparently everything is working fine. iOS: Header "jump" on first interaction with each bottom bar button, back animation looks good.
> 
> Tested with `@react-navigation/stack`. I quickly tried it with `@react-navigation/native-stack` but the screen content disappear.

@gloredo I have the same situation; Android is fine, iOS header (and content) flickers. Did you find any solution?

**Comment by gloredo** [comment]
@ansmlc not yet

**Comment by raajnadar** [comment]
This is the main reason for flicker issue --

- Improper react navigation configuration dependant libraries like reanimated, gesture handler, etc.
- Having nested safe area views (When you have a safe area view and you use <Appbar.Header /> from react native paper as a child)
- The custom height not added for custom header height. https://reactnavigation.org/docs/stack-navigator/#specify-a-height-in-headerstyle-to-avoid-glitches.
- When you have non contrast root view color to your foreground color of navigator.

Check all the above things and let me know.

**Comment by ansmlc** [comment]
> This is the main reason for flicker issue --
> 
> * Improper react navigation configuration dependant libraries like reanimated, gesture handler, etc.
> * Having nested safe area views (When you have a safe area view and you use <Appbar.Header /> from react native paper as a child)
> * The custom height not added for custom header height. https://reactnavigation.org/docs/stack-navigator/#specify-a-height-in-headerstyle-to-avoid-glitches.
> * When you have non contrast root view color to your foreground color of navigator.
> 
> Check all the above things and let me know.

As far as I can tell none of the above applies to my case, but I’ve fixed tbe flicker by setting “lazy: false” on Tab.Navigator.

**Comment by erickgtzh** [comment]
For me worked set duration to '0'

```
  const animationConfig = {
    animation: 'timing',
    config: { duration: 0 },
  };
```

```
 <Example.Screen
        name="Example"
        component={Example}
        options={{
          transitionSpec: {
            open: animationConfig,
            close: animationConfig,
          }, // added
          headerShown: false,
        }}
      />
```

**Comment by gloredo** [comment]
During the update to SDK 49 I solved the iOS problem where the header "jumps" at the first interaction with each button on the bottom bar:

```jsx
const { top } = useSafeAreaInsets();

//react-native-paper v4
<Appbar.Header
  statusBarHeight={top}
</Appbar.Header>
```

Everything works fine now, no "flick" at any point. @satya164 I think we can close this.
